In [2]:
import pandas as pd
import re
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("../data/raw_procurements.csv")

In [4]:
df.head(2)

,title,referenceNumber,prevReferenceNo,noticeReferenceNumber,nextRefNo,nextExtended,nextModified,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
0,ΜΙΣΘΩΣΗ ΙΔΙΩΤΙΚΩΝ ΜΗΧΑΝΗΜΑΤΩΝ ΓΙΑ ΕΚΤΕΛΕΣΗ ΕΡΓ...,24SYMV014279531,NaN,NaN,NaN,NaN,NaN,2024-02-17T12:45:08.845,0023-09-17,0023-09-17,False,NaN,False,NaN,NaN,NaN,NaN,ΧΩΡΙΣ ΠΡΩΤΟΚΟΛΛΟ,997947718,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EL641,Βοιωτία,5013,ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ,6.0,Απευθείας ανάθεση (αρ.118/αρ. 328),NaN,NaN,NaN,NaN,Υπηρεσίες,NaN,NaN,NaN,NaN,NaN,NaN,Ψ2Κ37ΛΗ-ΡΚΜ,NaN,NaN,NaN,NaN,ΤΜΗΜΑ ΠΟΛΙΤΙΚΗΣ ΠΡΟΣΤΑΣΙΑΣ ΠΕ ΒΟΙΩΤΙΑΣ,ΦΑΝΗΣ ΣΠΑΝΟΣ - ΠΕΡΙΦΕΡΕΙΑΡΧΗΣ,159003964,ΒΙΕΝΝΑ ΧΡΙΣΤΙΝΑ,9721.6,7840.0,ΕΡΓΑΣΙΕΣ ΠΡΟΛΗΨΗΣ ΔΑΣΙΚΩΝ ΠΥΡΚΑΓΙΩΝ ΣΤΗΝ ΕΥΡΥ...,75251110-4,Υπηρεσίες πρόληψης πυρκαγιών,Δεν εμπίπτει στο ΕΣΔ,NaN,[]
1,ΜΙΣΘΩΣΗ ΙΔΙΩΤΙΚΩΝ ΜΗΧΑΝΗΜΑΤΩΝ ΓΙΑ ΕΚΤΕΛΕΣΗ ΕΡΓ...,24SYMV014279535,NaN,NaN,NaN,NaN,NaN,2024-02-17T13:01:47.182,0023-09-17,0023-09-17,False,NaN,False,NaN,NaN,NaN,NaN,ΧΩΡΙΣ ΠΡΩΤΟΚΟΛΛΟ,997947718,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EL641,Βοιωτία,5013,ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ,6.0,Απευθείας ανάθεση (αρ.118/αρ. 328),NaN,NaN,NaN,NaN,Υπηρεσίες,NaN,NaN,NaN,NaN,NaN,NaN,6ΜΡΠ7ΛΗ-ΗΡΦ,NaN,NaN,NaN,NaN,ΤΜΗΜΑ ΠΟΛΙΤΙΚΗΣ ΠΡΟΣΤΑΣΙΑΣ ΠΕ ΒΟΙΩΤΙΑΣ,ΦΑΝΗΣ ΣΠΑΝΟΣ - ΠΕΡΙΦΕΡΕΙΑΡΧΗΣ,071029611,ΚΑΡΡΑΣ ΧΑΡΑΛΑΜΠΟΣ,9721.6,7840.0,ΕΡΓΑΣΙΕΣ ΠΡΟΛΗΨΗΣ ΔΑΣΙΚΩΝ ΠΥΡΚΑΓΙΩΝ ΣΤΗΝ ΕΥΡΥ...,75251110-4,Υπηρεσίες πρόληψης πυρκαγιών,Δεν εμπίπτει στο ΕΣΔ,NaN,[]

In [7]:
df.prevReferenceNo.isna().value_counts()

prevReferenceNo
True     4909
False     332
Name: count, dtype: int64

In [8]:
df.nextRefNo.isna().value_counts()

nextRefNo
True     4946
False     295
Name: count, dtype: int64

In [40]:
for i, item in df.iterrows():
    if pd.notna(item["prevReferenceNo"]):
        matched_prev = df.loc[
            df["referenceNumber"] == item["prevReferenceNo"],
            ["referenceNumber", "organization_value", "totalCostWithoutVAT"]
        ]

        if not matched_prev.empty:
            print("CURRENT ROW:")
            print(item[["referenceNumber", "prevReferenceNo", "nextRefNo"]])
            print("WILL ZERO PREVIOUS CONTRACT:")
            print(matched_prev)
            print("-----")

    if pd.notna(item["nextRefNo"]):
        print("CURRENT ROW:")
        print(item[["referenceNumber", "prevReferenceNo", "nextRefNo"]])
        print("WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:")
        print(df.loc[[i], ["referenceNumber", "organization_value", "totalCostWithoutVAT"]])
        print("-----")

CURRENT ROW:
referenceNumber    25SYMV016269657
prevReferenceNo    23SYMV012598716
nextRefNo          25SYMV016269734
Name: 25, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
    referenceNumber     organization_value  totalCostWithoutVAT
25  25SYMV016269657  ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016269734
prevReferenceNo    25SYMV016269657
nextRefNo          25SYMV016992728
Name: 26, dtype: object
WILL ZERO PREVIOUS CONTRACT:
    referenceNumber     organization_value  totalCostWithoutVAT
25  25SYMV016269657  ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016269734
prevReferenceNo    25SYMV016269657
nextRefNo          25SYMV016992728
Name: 26, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
    referenceNumber     organization_value  totalCostWithoutVAT
26  25SYMV016269734  ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016992728
prevReferenceNo    25SYMV016269734
nextRefNo          25SYMV018229349
Name: 27, dtype: object
WILL ZERO PREVIOUS CONTRACT:
    referenceNumber     organization_value  totalCostWithoutVAT
26  25SYMV016269734  ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016992728
prevReferenceNo    25SYMV016269734
nextRefNo          25SYMV018229349
Name: 27, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
    referenceNumber     organization_value  totalCostWithoutVAT
27  25SYMV016992728  ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV018229349
prevReferenceNo    25SYMV016992728
nextRefNo                      NaN
Name: 28, dtype: object
WILL ZERO PREVIOUS CONTRACT:
    referenceNumber     organization_value  totalCostWithoutVAT
27  25SYMV016992728  ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014334702
prevReferenceNo                NaN
nextRefNo          24SYMV014646759
Name: 52, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
    referenceNumber          organization_value  totalCostWithoutVAT
52  24SYMV014334702  ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014646759
prevReferenceNo    24SYMV014334702
nextRefNo                      NaN
Name: 55, dtype: object
WILL ZERO PREVIOUS CONTRACT:
    referenceNumber          organization_value  totalCostWithoutVAT
52  24SYMV014334702  ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014109048
prevReferenceNo    23SYMV013661832
nextRefNo          24SYMV014796067
Name: 133, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
133  24SYMV014109048  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
133                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014796067
prevReferenceNo    24SYMV014109048
nextRefNo          24SYMV015476714
Name: 134, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
133  24SYMV014109048  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
133                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014796067
prevReferenceNo    24SYMV014109048
nextRefNo          24SYMV015476714
Name: 134, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
134  24SYMV014796067  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
134                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV015476714
prevReferenceNo    24SYMV014796067
nextRefNo          25SYMV016310914
Name: 135, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
134  24SYMV014796067  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
134                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV015476714
prevReferenceNo    24SYMV014796067
nextRefNo          25SYMV016310914
Name: 135, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
135  24SYMV015476714  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
135                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016310914
prevReferenceNo    24SYMV015476714
nextRefNo          25SYMV017084945
Name: 136, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
135  24SYMV015476714  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
135                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016310914
prevReferenceNo    24SYMV015476714
nextRefNo          25SYMV017084945
Name: 136, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
136  25SYMV016310914  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
136                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV017084945
prevReferenceNo    25SYMV016310914
nextRefNo          25SYMV018016294
Name: 137, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
136  25SYMV016310914  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
136                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV017084945
prevReferenceNo    25SYMV016310914
nextRefNo          25SYMV018016294
Name: 137, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
137  25SYMV017084945  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
137                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV018016294
prevReferenceNo    25SYMV017084945
nextRefNo                      NaN
Name: 138, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
137  25SYMV017084945  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
137                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014235036
prevReferenceNo                NaN
nextRefNo          24SYMV014514618
Name: 182, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
182  24SYMV014235036  Ο.ΣΥ. Α.Ε. - ΟΔΙΚΕΣ ΣΥΓΚΟΙΝΩΝΙΕΣ Α.Ε.

     totalCostWithoutVAT
182                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014514618
prevReferenceNo    24SYMV014235036
nextRefNo                      NaN
Name: 183, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
182  24SYMV014235036  Ο.ΣΥ. Α.Ε. - ΟΔΙΚΕΣ ΣΥΓΚΟΙΝΩΝΙΕΣ Α.Ε.

     totalCostWithoutVAT
182                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014214427
prevReferenceNo    23SYMV013767520
nextRefNo          24SYMV014802054
Name: 252, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
252  24SYMV014214427     ΔΗΜΟΣ ΛΕΒΑΔΕΩΝ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014257531
prevReferenceNo                NaN
nextRefNo          25SYMV017076060
Name: 272, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber               organization_value  totalCostWithoutVAT
272  24SYMV014257531  ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV017076060
prevReferenceNo    24SYMV014257531
nextRefNo                      NaN
Name: 277, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber               organization_value  totalCostWithoutVAT
272  24SYMV014257531  ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014721828
prevReferenceNo                NaN
nextRefNo          24SYMV014818537
Name: 322, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber          organization_value  totalCostWithoutVAT
322  24SYMV014721828  ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014818537
prevReferenceNo    24SYMV014721828
nextRefNo                      NaN
Name: 323, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber          organization_value  totalCostWithoutVAT
322  24SYMV014721828  ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014399368
prevReferenceNo                NaN
nextRefNo          25SYMV016438247
Name: 330, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber             organization_value  totalCostWithoutVAT
330  24SYMV014399368  4Η ΔΥΠΕ ΜΑΚΕΔΟΝΙΑΣ ΚΑΙ ΘΡΑΚΗΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014539052
prevReferenceNo                NaN
nextRefNo          25SYMV016865210
Name: 351, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                 organization_value  \
351  24SYMV014539052  ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ...

     totalCostWithoutVAT
351                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014594451
prevReferenceNo                NaN
nextRefNo          25SYMV016873543
Name: 352, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                 organization_value  \
352  24SYMV014594451  ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ...

     totalCostWithoutVAT
352                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014908446
prevReferenceNo                NaN
nextRefNo          25SYMV016790893
Name: 353, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                 organization_value  \
353  24SYMV014908446  ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ...

     totalCostWithoutVAT
353                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016790893
prevReferenceNo    24SYMV014908446
nextRefNo                      NaN
Name: 354, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                                 organization_value  \
353  24SYMV014908446  ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ...

     totalCostWithoutVAT
353                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016865210
prevReferenceNo    24SYMV014539052
nextRefNo                      NaN
Name: 355, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                                 organization_value  \
351  24SYMV014539052  ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ...

     totalCostWithoutVAT
351                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016873543
prevReferenceNo    24SYMV014594451
nextRefNo                      NaN
Name: 356, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                                 organization_value  \
352  24SYMV014594451  ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ...

     totalCostWithoutVAT
352                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014463876
prevReferenceNo    23SYMV013192663
nextRefNo          24SYMV014806991
Name: 374, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
374  24SYMV014463876  ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014463428
prevReferenceNo                NaN
nextRefNo          24SYMV015283291
Name: 386, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
386  24SYMV014463428       ΔΗΜΟΣ ΔΡΑΜΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014482583
prevReferenceNo                NaN
nextRefNo          24SYMV014499738
Name: 399, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
399  24SYMV014482583        ΔΗΜΟΣ ΥΔΡΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014499738
prevReferenceNo    24SYMV014482583
nextRefNo                      NaN
Name: 404, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber organization_value  totalCostWithoutVAT
399  24SYMV014482583        ΔΗΜΟΣ ΥΔΡΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014503382
prevReferenceNo                NaN
nextRefNo          24SYMV014763416
Name: 411, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                organization_value  \
411  24SYMV014503382  ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ

     totalCostWithoutVAT
411                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014763416
prevReferenceNo    24SYMV014503382
nextRefNo                      NaN
Name: 413, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                                organization_value  \
411  24SYMV014503382  ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ

     totalCostWithoutVAT
411                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014522917
prevReferenceNo                NaN
nextRefNo          24SYMV015147098
Name: 420, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber    organization_value  totalCostWithoutVAT
420  24SYMV014522917  ΥΠΟΥΡΓΕΙΟ ΠΟΛΙΤΙΣΜΟΥ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV015147098
prevReferenceNo    24SYMV014522917
nextRefNo                      NaN
Name: 425, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber    organization_value  totalCostWithoutVAT
420  24SYMV014522917  ΥΠΟΥΡΓΕΙΟ ΠΟΛΙΤΙΣΜΟΥ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014559261
prevReferenceNo                NaN
nextRefNo          24SYMV014795318
Name: 441, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                 organization_value  \
441  24SYMV014559261  ΟΡΓΑΝΙΣΜΟΣ ΦΥΣΙΚΟΥ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΚΛΙΜΑΤΙΚΗ...

     totalCostWithoutVAT
441                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014579086
prevReferenceNo    23SYMV013727653
nextRefNo          24SYMV014671822
Name: 444, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber  organization_value  totalCostWithoutVAT
444  24SYMV014579086  ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ                  0.0
-----
CURRENT ROW:
referenceNumber    25SYMV016679557
prevReferenceNo    24SYMV014633637
nextRefNo                      NaN
Name: 451, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                     organization_value  \
513  24SYMV014633637  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
513                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014624651
prevReferenceNo                NaN
nextRefNo          24SYMV014624658
Name: 503, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber        organization_value  totalCostWithoutVAT
503  24SYMV014624651  ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗΣ ΑΜΥΝΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014624658
prevReferenceNo    24SYMV014624651
nextRefNo                      NaN
Name: 504, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber        organization_value  totalCostWithoutVAT
503  24SYMV014624651  ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗΣ ΑΜΥΝΑΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014633637
prevReferenceNo                NaN
nextRefNo          25SYMV016679557
Name: 513, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                     organization_value  \
513  24SYMV014633637  ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ

     totalCostWithoutVAT
513                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014656277
prevReferenceNo                NaN
nextRefNo          24SYMV015692196
Name: 534, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber    organization_value  totalCostWithoutVAT
534  24SYMV014656277  ΥΠΟΥΡΓΕΙΟ ΠΟΛΙΤΙΣΜΟΥ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014671822
prevReferenceNo    24SYMV014579086
nextRefNo          24SYMV014964727
Name: 554, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber  organization_value  totalCostWithoutVAT
444  24SYMV014579086  ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014671822
prevReferenceNo    24SYMV014579086
nextRefNo          24SYMV014964727
Name: 554, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber  organization_value  totalCostWithoutVAT
554  24SYMV014671822  ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014680813
prevReferenceNo                NaN
nextRefNo          24SYMV014892370
Name: 561, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                organization_value  \
561  24SYMV014680813  ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ

     totalCostWithoutVAT
561                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014775715
prevReferenceNo    23SYMV012620288
nextRefNo          24SYMV016100644
Name: 565, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
565  24SYMV014775715   ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΗΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014776662
prevReferenceNo    23SYMV012776057
nextRefNo          24SYMV016100976
Name: 566, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
566  24SYMV014776662   ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΗΣ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014892370
prevReferenceNo    24SYMV014680813
nextRefNo          24SYMV014985785
Name: 567, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                                organization_value  \
561  24SYMV014680813  ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ

     totalCostWithoutVAT
561                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014892370
prevReferenceNo    24SYMV014680813
nextRefNo          24SYMV014985785
Name: 567, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber                                organization_value  \
567  24SYMV014892370  ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ

     totalCostWithoutVAT
567                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014985785
prevReferenceNo    24SYMV014892370
nextRefNo                      NaN
Name: 568, dtype: object
WILL ZERO PREVIOUS CONTRACT:
     referenceNumber                                organization_value  \
567  24SYMV014892370  ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ

     totalCostWithoutVAT
567                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV014693830
prevReferenceNo                NaN
nextRefNo          24SYMV015860585
Name: 580, dtype: object
WILL ALSO ZERO THIS CURRENT CONTRACT BECAUSE IT HAS nextRefNo:
     referenceNumber organization_value  totalCostWithoutVAT
580  24SYMV014693830        ΔΗΜΟΣ ΙΛΙΟΥ                  0.0
-----
CURRENT ROW:
referenceNumber    24SYMV015860585
prevReferenceNo    24SYMV014693830
nextRefNo                      NaN
Name: 600, dtype: object

In [36]:
print(df.loc[df["referenceNumber"].isin(df["prevReferenceNo"].dropna()), ["referenceNumber", "totalCostWithoutVAT"]])
print(df.loc[df["nextRefNo"].notna(), ["referenceNumber", "totalCostWithoutVAT"]])

      referenceNumber  totalCostWithoutVAT
25    25SYMV016269657            124185.11
26    25SYMV016269734            124185.11
27    25SYMV016992728            124185.11
52    24SYMV014334702              2140.00
133   24SYMV014109048            113387.10
...               ...                  ...
5024  25SYMV018048896             14516.00
5058  25SYMV018097386             54354.72
5062  25SYMV018087483             29700.00
5065  26SYMV018322847             10000.00
5143  25SYMV018273017             16863.00

[288 rows x 2 columns]
      referenceNumber  totalCostWithoutVAT
25    25SYMV016269657            124185.11
26    25SYMV016269734            124185.11
27    25SYMV016992728            124185.11
52    24SYMV014334702              2140.00
133   24SYMV014109048            113387.10
...               ...                  ...
5024  25SYMV018048896             14516.00
5058  25SYMV018097386             54354.72
5062  25SYMV018087483             29700.00
5065  26SYMV018322847             10000.00
5143  25SYMV018273017             16863.00

[295 rows x 2 columns]

In [39]:
df.totalCostWithoutVAT.sum()

np.float64(739508544.78)

In [38]:
df.loc[df["referenceNumber"].isin(df["prevReferenceNo"].dropna()), "totalCostWithoutVAT"] = 0
df.loc[df["nextRefNo"].notna(), "totalCostWithoutVAT"] = 0

In [41]:
df[df.referenceNumber=="25SYMV018229349"]

,title,referenceNumber,prevReferenceNo,noticeReferenceNumber,nextRefNo,nextExtended,nextModified,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
28,Βελτίωση δασικών δρόμων για αντιπυρική προστασία,25SYMV018229349,25SYMV016992728,NaN,NaN,NaN,NaN,2025-12-22T11:15:28.174,2023-05-02,2023-05-02,False,2025-08-02,False,NaN,NaN,NaN,ΨΒ4ΥΩΛΥ-0ΑΒ,14,997648480,True,NaN,NaN,153989.54,1.0,NaN,1.0,Όχι,EL611,"Καρδίτσα, Τρίκαλα",6175,ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ,1.0,Ανοιχτή διαδικασία,NaN,ΜΟΡΦΟΒΟΥΝΙ,43150,Δεν χρησιμοποιείται,Έργα,Βάσει τιμής,ΟΤΑ,ΝΠΔΔ,Γενικές δημόσιες υπηρεσίες,5.0,NaN,Ψ24ΞΩΛΥ-ΗΝ8 | Ψ24ΞΩΛΥ-ΗΝ8 | ΨΩ86ΩΛΥ-ΠΒΛ,NaN,NaN,NaN,64-7341.03,ΔΗΜΟΤΙΚΟ ΣΥΜΒΟΥΛΙΟ,ΠΑΝΑΓΙΩΤΗΣ ΝΑΝΟΣ - Δήμαρχος,134221428,ΜΠΡΙΑΝΑ ΔΕΣΠΟΙΝΑ,153989.54,124185.11,Το συγκεκριμένο έργο αφορά παρεμβάσεις στο υπά...,45233120-6,Έργα οδοποιίας,Δεν εμπίπτει στο ΕΣΔ,NaN,[]

In [42]:
df[df.referenceNumber=="25SYMV018289789"]

,title,referenceNumber,prevReferenceNo,noticeReferenceNumber,nextRefNo,nextExtended,nextModified,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
5154,Σύνταξη Σχεδίων Πολιτικής Προστασίας Και Διαχε...,25SYMV018289789,NaN,NaN,NaN,NaN,NaN,2025-12-31T12:19:59.827,2025-12-31,2025-12-31,False,2026-03-31,False,NaN,NaN,NaN,NaN,8749,997687953,True,NaN,NaN,5300.0,1.0,NaN,1.0,Όχι,EL513,Ροδόπη,6117,ΔΗΜΟΣ ΙΑΣΜΟΥ,6.0,Απευθείας ανάθεση,NaN,ΙΑΣΜΟΣ,69200,Δεν χρησιμοποιείται,Υπηρεσίες,Βάσει τιμής,ΟΤΑ,ΝΠΔΔ,Γενικές δημόσιες υπηρεσίες,3.0,NaN,Ψ86ΙΩΡΧ-ΨΞΦ,NaN,NaN,NaN,0611.001,ΚΕΝΤΡΙΚΗ ΥΠΗΡΕΣΙΑ,ΤΖΑΝΕΡ ΙΜΑΜ - Δήμαρχος,099081263,ΦΟΡΟΥΜ ΔΙΕΘΝΗΣ ΕΠΙΜΟΡΦΩΤΙΚΗ ΚΑΙ ΣΥΜΒΟΥΛΕΥΤΙΚΗ ΕΠΕ,6572.0,5300.0,Σύνταξη Σχεδίων Πολιτικής Προστασίας Και Διαχε...,79415200-8,Υπηρεσίες παροχής συμβουλών σε θέματα σχεδιασμού,Δεν εμπίπτει στο ΕΣΔ,25AWRD018256232,[]