In [150]:
import pandas as pd
import re
import requests
from datetime import date, timedelta
import unicodedata
import json
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option("display.max_colwidth", None)

In [151]:
from unicodedata import normalize as uninorm

def normalize_string(s):
    if not isinstance(s, str):
        return s
    s = s.lower()
    s = uninorm("NFD", s)
    s = "".join(c for c in s if __import__('unicodedata').category(c) != "Mn")
    s = " ".join(s.split())
    return s
# True

In [152]:
df = pd.read_csv("../data/raw_procurements.csv")
DEFAULT_CPVS: dict[str, str] = {
    "75251100-1": "Υπηρεσίες καταπολέμησης πυρκαγιών",
    "75251110-4": "Υπηρεσίες πρόληψης πυρκαγιών",
    "75251120-7": "Υπηρεσίες καταπολέμησης δασοπυρκαγιών",
    "77200000-2": "Υπηρεσίες δασοκομίας",
    "77312000-0": "Υπηρεσίες εκκαθάρισης από αγριόχορτα",
    "77314000-4": "Υπηρεσίες συντήρησης οικοπέδων",
    "77340000-5": "Κλάδεμα δένδρων και θάμνων",
    "45343000-3": "Εργασίες εγκαταστάσεων πρόληψης πυρκαγιάς",
    "77314100-5": "Υπηρεσίες χορτοκάλυψης",
    "34144200-0": "Οχήματα για τις υπηρεσίες εκτάκτου ανάγκης",
    "34144212-7": "Υδροφόρες πυροσβεστικών οχημάτων",
    "35111000-5": "Πυροσβεστικός εξοπλισμός",
    "35111200-7": "Υλικά πυρόσβεσης",
    "44480000-8": "Ποικίλος εξοπλισμός πυροπροστασίας"
}

In [149]:
df[df.organization_value.str.contains("Λαγκαδ", case=False)]

,title,referenceNumber,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
4006,ΠΡΟΜΗΘΕΙΑΣ ΕΝΟΣ ΠΥΡΟΣΒΕΣΤΙΚΟΥ ΕΞΟΠΛΙΣΜΟΥ -ΤΜΗΜΑ 3,26SYMV018473491,2026-02-12T13:20:49.151,2026-02-12,2026-02-12,False,2026-10-12,False,NaN,NaN,NaN,NaN,3843,998246659,True,NaN,NaN,290322.58,NaN,1.0,3.0,Όχι,EL522,Θεσσαλονίκη,6165,ΔΗΜΟΣ ΛΑΓΚΑΔΑ,1.0,Ανοιχτή διαδικασία,NaN,ΛΑΓΚΑΔΑ,572 00,Δεν χρησιμοποιείται,Προμήθειες,Βάσει τιμής,ΟΤΑ,ΝΠΔΔ,Γενικές δημόσιες υπηρεσίες,8.0,Μήνες,9ΞΘΔΩΛΛ-3ΟΝ,NaN,NaN,NaN,NaN,ΠΡΟΜΗΘΕΙΩΝ,ΕΛΠΙΝΙΚΗ ΑΝΔΡΕΑΔΟΥ - Δήμαρχος,801083010,C. I. PARTS Ι.Κ.Ε.,17360.0,14000.0,ΠΡΟΜΗΘΕΙΑΣ ΕΝΟΣ ΠΥΡΟΣΒΕΣΤΙΚΟΥ ΕΞΟΠΛΙΣΜΟΥ -ΤΜΗΜΑ 3,35111000-5,Πυροσβεστικός εξοπλισμός,Δεν εμπίπτει στο ΕΣΔ,25AWRD018061107,[]
4009,"ΠΡΟΜΗΘΕΙΑΣ ΕΝΟΣ (1) ΒΥΤΙΟΦΟΡΟΥ ΟΧΗΜΑΤΟΣ, ΣΤΟ ΔΗΜΟ ΛΑΓΚΑΔΑ- ΤΜΗΜΑ 1",26SYMV018491493,2026-02-17T09:45:20.6,2026-02-16,2026-02-16,False,2026-08-16,False,NaN,NaN,NaN,NaN,4163,998246659,True,NaN,NaN,290322.58,NaN,1.0,3.0,Όχι,EL522,Θεσσαλονίκη,6165,ΔΗΜΟΣ ΛΑΓΚΑΔΑ,1.0,Ανοιχτή διαδικασία,NaN,ΛΑΓΚΑΔΑ,572 00,Δεν χρησιμοποιείται,Προμήθειες,Βάσει τιμής,ΟΤΑ,ΝΠΔΔ,Γενικές δημόσιες υπηρεσίες,6.0,Μήνες,9ΞΘΔΩΛΛ-3ΟΝ,NaN,NaN,NaN,NaN,ΠΡΟΜΗΘΕΙΩΝ,ΕΛΠΙΝΙΚΗ ΑΝΔΡΕΑΔΟΥ - Δήμαρχος,094270233,ΕΛΛΗΝΙΚΗ ΒΙΟΜΗΧΑΝΙΑ ΠΕΡΙΒΑΛΟΝΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ-ΑΝΩΝΥΜΗ ΕΜΠΟΡΙΚΗ - ΒΙΟΜΗΧΑΝΙΚΗ ΕΤΑΙΡΕΙΑ ΑΕΒΕ,227912.0,183800.0,"ΠΡΟΜΗΘΕΙΑΣ ΕΝΟΣ (1) ΒΥΤΙΟΦΟΡΟΥ ΟΧΗΜΑΤΟΣ, ΣΤΟ ΔΗΜΟ ΛΑΓΚΑΔΑ, ΠΟΣΟΥ 227.912,00 με Φ.Π.Α. 24%- ΤΜΗΜΑ 1",34144212-7,Υδροφόρες πυροσβεστικών οχημάτων,Δεν εμπίπτει στο ΕΣΔ,25AWRD018061107,[]

In [175]:
df.contractType.value_counts()

contractType
Υπηρεσίες                               3119
Προμήθειες                               713
Έργα                                     125
Τεχνικές ή λοιπές συναφείς υπηρεσίες      54
Μελέτες                                   10
Name: count, dtype: int64

In [179]:
pd.options.display.float_format = '{:,.2f}'.format
df.groupby("organization_value")['totalCostWithoutVAT'].sum().sort_values(ascending=False)

organization_value
ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ                                                                                      438,269,333.89
ΥΠΟΥΡΓΕΙΟ ΚΛΙΜΑΤΙΚΗΣ ΚΡΙΣΗΣ ΚΑΙ ΠΟΛΙΤΙΚΗΣ ΠΡΟΣΤΑΣΙΑΣ                                                                       159,835,424.63
ΚΟΙΝΩΝΙΑ ΤΗΣ ΠΛΗΡΟΦΟΡΙΑΣ ΑΕ                                                                                                 25,768,800.00
ΠΕΡΙΦΕΡΕΙΑ ΑΤΤΙΚΗΣ                                                                                                          17,849,223.09
ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΗΣ                                                                                                            14,174,847.13
ΑΝΕΞΑΡΤΗΤΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΜΕΤΑΦΟΡΑΣ ΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ ΑΔΜΗΕ ΑΕ                                                             9,045,258.58
ΔΗΜΟΣ ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ                                                                                          5,833,607.78
ΕΥΔΑΠ ΑΕ                                                                                                                     5,542,912.70
3Η ΔΥΠΕ ΜΑΚΕΔΟΝΙΑΣ                                                                                                           5,025,968.94
ΔΗΜΟΣ ΧΙΟΥ                                                                                                                   3,008,037.86
ΥΠΟΥΡΓΕΙΟ ΠΟΛΙΤΙΣΜΟΥ                                                                                                         2,944,473.14
ΠΕΡΙΦΕΡΕΙΑ ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ - ΘΡΑΚΗΣ                                                                                    2,781,586.40
ΠΕΡΙΦΕΡΕΙΑ ΝΟΤΙΟΥ ΑΙΓΑΙΟΥ                                                                                                    2,722,352.48
ΔΗΜΟΣ ΠΑΤΡΕΩΝ                                                                                                                2,473,060.40
ΠΕΡΙΦΕΡΕΙΑ ΗΠΕΙΡΟΥ                                                                                                           2,429,778.77
ΔΗΜΟΣ ΚΑΛΛΙΘΕΑΣ                                                                                                              2,365,960.36
ΔΗΜΟΣ ΑΘΗΝΑΙΩΝ                                                                                                               2,358,491.43
ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ                                                                                              2,221,525.24
ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ                                                                                                   2,118,383.34
ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗΣ ΑΜΥΝΑΣ                                                                                                     1,710,448.61
ΔΗΜΟΣ ΑΣΠΡΟΠΥΡΓΟΥ                                                                                                            1,642,171.00
ΔΗΜΟΣ ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ                                                                                            1,637,405.41
ΥΠΟΥΡΓΕΙΟ ΝΑΥΤΙΛΙΑΣ ΚΑΙ ΝΗΣΙΩΤΙΚΗΣ ΠΟΛΙΤΙΚΗΣ                                                                                 1,634,459.04
ΟΡΓΑΝΙΣΜΟΣ ΣΙΔΗΡΟΔΡΟΜΩΝ ΕΛΛΑΔΑΣ (ΟΣΕ)                                                                                        1,539,822.06
ΔΗΜΟΣ ΠΑΛΛΗΝΗΣ                                                                                                               1,267,930.39
ΔΗΜΟΣ ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ                                                                                                        1,201,005.84
ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ                                                                                                            1,159,184.30
ΔΗΜΟΣ ΧΑΛΚΙΔΕΩΝ                                                                                                              1,078,626.02
ΔΗΜΟΣ ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ                                                                                                    1,017,707.28
ΔΗΜΟΣ ΘΕΡΜΗΣ                                                                                                                   998,279.41
ΣΥΝΔΕΣΜΟΣ ΠΡΟΣΤΑΣΙΑΣ ΚΑΙ ΑΝΑΠΤΥΞΗΣ ΥΜΗΤΤΟΥ                                                                                     940,698.50
ΗΔΙΚΑ Α.Ε (ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΑΚΥΒΕΡΝΗΣΗ - ΚΟΙΝΩΝΙΚΗ ΑΣΦΑΛΙΣΗ Α.Ε)                                                                  837,604.61
ΔΗΜΟΣ ΓΛΥΦΑΔΑΣ                                                                                                                 828,792.55
ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ                                                                                                              797,590.15
ΔΗΜΟΣ ΜΕΓΑΡΕΩΝ                                                                                                                 782,757.77
ΔΗΜΟΣ ΑΛΜΥΡΟΥ                                                                                                                  762,433.99
ΔΗΜΟΣ ΚΑΒΑΛΑΣ                                                                                                                  759,647.91
ΔΗΜΟΣ ΚΑΛΑΜΑΡΙΑΣ                                                                                                               705,427.76
ΔΗΜΟΣ ΡΟΔΟΥ                                                                                                                    603,236.00
ΔΗΜΟΣ ΦΙΛΙΑΤΩΝ                                                                                                                 578,383.37
ΠΕΡΙΦΕΡΕΙΑ ΘΕΣΣΑΛΙΑΣ                                                                                                           523,648.38
ΔΗΜΟΣΙΑ ΥΠΗΡΕΣΙΑ ΑΠΑΣΧΟΛΗΣΗΣ                                                                                                   505,024.80
ΕΛΛΗΝΙΚΑ ΑΜΥΝΤΙΚΑ ΣΥΣΤΗΜΑΤΑ  ΑΒΕΕ                                                                                              494,830.00
ΠΕΡΙΦΕΡΕΙΑ ΔΥΤΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ                                                                                                  464,870.00
ΔΗΜΟΣ ΑΓΡΙΝΙΟΥ                                                                                                                 458,313.02
ΔΗΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ                                                                                                              454,785.83
ΔΗΜΟΣ ΠΑΥΛΟΥ ΜΕΛΑ                                                                                                              440,186.45
ΔΗΜΟΣ ΣΙΚΥΩΝΙΩΝ                                                                                                                434,844.20
ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ                                                                                                                 419,484.27
ΔΗΜΟΣ ΔΡΑΜΑΣ                                                                                                                   412,665.54
ΔΗΜΟΣ ΚΡΩΠΙΑΣ                                                                                                                  403,134.05
ΔΗΜΟΣ ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ                                                                                                       398,907.86
ΠΕΡΙΦΕΡΕΙΑ ΒΟΡΕΙΟΥ ΑΙΓΑΙΟΥ                                                                                                     395,771.30
ΔΗΜΟΣ ΟΡΧΟΜΕΝΟΥ                                                                                                                391,708.32
ΔΗΜΟΣ ΧΑΛΑΝΔΡΙΟΥ                                                                                                               377,300.07
ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΑΧΑΙΑΣ                                                                                                           371,863.58
ΔΗΜΟΣ ΕΡΥΜΑΝΘΟΥ                                                                                                                365,944.46
ΔΗΜΟΣ ΒΥΡΩΝΟΣ                                                                                                                  356,168.82
ΥΠΟΥΡΓΕΙΟ ΥΠΟΔΟΜΩΝ ΚΑΙ ΜΕΤΑΦΟΡΩΝ                                                                                               345,077.54
ΔΗΜΟΣ ΡΕΘΥΜΝΗΣ                                                                                                                 338,106.77
ΔΗΜΟΣ ΝΕΑΣ ΠΡΟΠΟΝΤΙΔΑΣ                                                                                                         337,588.00
ΔΗΜΟΣ ΣΕΡΡΩΝ                                                                                                                   332,156.43
ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΛΕΣΒΟΥ                                                                                                           329,011.09
ΠΕΡΙΦΕΡΕΙΑ ΠΕΛΟΠΟΝΝΗΣΟΥ                                                                                                        323,039.76
ΔΗΜΟΣ ΤΡΙΠΟΛΗΣ                                                                                                                 313,176.82
ΔΗΜΟΣ ΚΕΝΤΡΙΚΗΣ ΚΕΡΚΥΡΑΣ ΚΑΙ ΔΙΑΠΟΝΤΙΩΝ ΝΗΣΩΝ                                                                                  312,234.81
ΔΗΜΟΣ ΑΡΓΟΣΤΟΛΙΟΥ                                                                                                              311,825.31
ΦΟΡΕΑΣ ΔΙΑΧΕΙΡΙΣΗΣ ΜΗΤΡΟΠΟΛΙΤΙΚΟΥ ΠΑΡΚΟΥ ΠΕΡΙΒΑΛΛΟΝΤΙΚΩΝ ΚΑΙ ΕΚΠΑΙΔΕΥΤΙΚΩΝ ΔΡΑΣΤΗΡΙΟΤΗΤΩΝ ΚΑΙ ΑΝΑΠΤΥΞΗΣ ΚΟΙΝΩΝΙΚΗΣ ΟΙΚΟΝ       310,259.17
ΔΗΜΟΣ ΑΧΑΡΝΩΝ                                                                                                                  305,150.79
ΔΗΜΟΤΙΚΗ ΕΠΙΧΕΙΡΗΣΗ ΥΔΡΕΥΣΗΣ ΑΠΟΧΕΤΕΥΣΗΣ ΔΗΜΟΥ ΡΟΔΟΥ (Δ.Ε.Υ.ΑΡ)                                                                294,000.00
ΔΗΜΟΣ ΠΑΙΟΝΙΑΣ                                                                                                                 289,941.93
ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ                                                                                                          284,498.21
ΔΗΜΟΣ ΒΟΛΒΗΣ                                                                                                                   283,838.68
ΔΗΜΟΣ ΔΕΛΦΩΝ                                                                                                                   282,150.70
ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ                                                                                                               276,358.16
ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΜΑΝΗΣ                                                                                                            276,118.52
ΔΗΜΟΣ ΝΑΞΟΥ & ΜΙΚΡΩΝ ΚΥΚΛΑΔΩΝ                                                                                                  275,687.06
ΔΗΜΟΣ ΜΥΤΙΛΗΝΗΣ                                                                                                                271,089.68
ΔΗΜΟΣ ΒΕΡΟΙΑΣ                                                                                                                  268,669.51
ΔΗΜΟΣ ΜΑΡΑΘΩΝΟΣ                                                                                                                268,565.44
ΔΗΜΟΣ ΤΑΝΑΓΡΑΣ                                                                                                                 256,879.00
ΓΑΙΑ ΟΣΕ ΑΕ                                                                                                                    255,120.00
ΔΗΜΟΣ ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ                                                                                                       250,408.92
ΔΗΜΟΤΙΚΟ ΛΙΜΕΝΙΚΟ ΤΑΜΕΙΟ ΣΚΑΛΑΣ ΩΡΩΠΟΥ                                                                                         246,272.40
ΔΗΜΟΣ ΑΙΓΙΑΛΕΙΑΣ                                                                                                               245,192.86
ΔΗΜΟΣ ΚΑΛΑΜΑΤΑΣ                                                                                                                240,082.95
ΔΗΜΟΣ ΝΕΑΠΟΛΗΣ - ΣΥΚΕΩΝ                                                                                                        231,754.92
ΔΗΜΟΣ ΠΟΛΥΓΥΡΟΥ                                                                                                                224,899.91
ΔΗΜΟΣ ΧΑΝΙΩΝ                                                                                                                   222,463.97
ΗΛΕΚΤΡΟΝΙΚΟΣ ΕΘΝΙΚΟΣ ΦΟΡΕΑΣ ΚΟΙΝΩΝΙΚΗΣ ΑΣΦΑΛΙΣΗΣ                                                                               220,291.00
ΠΕΡΙΦΕΡΕΙΑ ΔΥΤΙΚΗΣ ΕΛΛΑΔΑΣ                                                                                                     219,857.07
ΔΗΜΟΣ ΙΩΑΝΝΙΤΩΝ                                                                                                                217,133.91
ΔΗΜΟΣ ΠΑΙΑΝΙΑΣ                                                                                                                 216,200.54
ΠΕΡΙΦΕΡΕΙΑ ΙΟΝΙΩΝ ΝΗΣΩΝ                                                                                                        209,800.00
ΔΗΜΟΣ ΔΙΟΥ - ΟΛΥΜΠΟΥ                                                                                                           208,980.00
ΔΗΜΟΣ ΝΕΑΣ ΖΙΧΝΗΣ                                                                                                              206,175.20
ΔΗΜΟΣ ΠΕΝΤΕΛΗΣ                                                                                                                 205,958.48
ΔΗΜΟΣ ΛΑΓΚΑΔΑ                                                                                                                  197,800.00
ΔΗΜΟΣ ΚΑΛΑΒΡΥΤΩΝ                                                                                                               194,478.28
Ο.ΣΥ. Α.Ε. - ΟΔΙΚΕΣ ΣΥΓΚΟΙΝΩΝΙΕΣ Α.Ε.                                                                                          192,444.00
ΟΡΓΑΝΙΣΜΟΣ ΦΥΣΙΚΟΥ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΚΛΙΜΑΤΙΚΗΣ ΑΛΛΑΓΗΣ                                                                        186,545.79
ΔΗΜΟΣ ΛΑΜΙΕΩΝ                                                                                                                  184,710.50
ΕΤΑΙΡΕΙΑ ΥΔΡΕΥΣΗΣ ΑΠΟΧΕΤΕΥΣΗΣ ΘΕΣΣΑΛΟΝΙΚΗΣ (ΕΥΑΘ ΑΕ)                                                                           179,809.00
ΔΗΜΟΣ ΔΟΜΟΚΟΥ                                                                                                                  179,626.06
ΔΗΜΟΣ ΚΑΤΕΡΙΝΗΣ                                                                                                                178,675.00
ΔΗΜΟΣ ΚΗΦΙΣΙΑΣ                                                                                                                 176,667.30
ΔΗΜΟΣ ΕΛΕΥΣΙΝΑΣ                                                                                                                174,040.79
ΔΗΜΟΣ ΜΕΓΑΛΟΠΟΛΗΣ                                                                                                              172,244.96
ΔΗΜΟΣ ΑΜΦΙΛΟΧΙΑΣ                                                                                                               170,993.36
ΔΗΜΟΣ ΛΕΥΚΑΔΑΣ                                                                                                                 169,901.12
ΠΕΡΙΦΕΡΕΙΑ ΚΡΗΤΗΣ                                                                                                              168,996.36
ΔΗΜΟΣ ΒΟΙΟΥ                                                                                                                    166,096.00
ΔΗΜΟΣ ΑΡΧΑΝΩΝ - ΑΣΤΕΡΟΥΣΙΩΝ                                                                                                    164,391.20
ΙΕΡΑ ΜΗΤΡΟΠΟΛΙΣ ΙΩΑΝΝΙΝΩΝ                                                                                                      160,000.00
ΔΗΜΟΣ ΠΕΛΛΑΣ                                                                                                                   159,822.00
ΔΗΜΟΣ ΕΠΙΔΑΥΡΟΥ                                                                                                                156,159.11
ΔΗΜΟΣ ΔΩΔΩΝΗΣ                                                                                                                  156,152.00
ΔΗΜΟΣ ΚΟΡΙΝΘΙΩΝ                                                                                                                154,507.56
ΔΗΜΟΣ ΑΡΧΑΙΑΣ ΟΛΥΜΠΙΑΣ                                                                                                         153,875.72
ΔΗΜΟΣ ΘΗΒΑΙΩΝ                                                                                                                  149,880.00
ΔΗΜΟΣ ΣΑΛΑΜΙΝΑΣ                                                                                                                147,499.25
ΔΗΜΟΣ ΝΟΤΙΑΣ ΚΥΝΟΥΡΙΑΣ                                                                                                         146,950.00
ΔΗΜΟΣ ΣΑΜΗΣ                                                                                                                    144,870.00
ΔΗΜΟΣ ΑΡΓΟΥΣ - ΜΥΚΗΝΩΝ                                                                                                         142,046.00
ΙΔΡΥΜΑ ΝΕΟΛΑΙΑΣ ΚΑΙ ΔΙΑ ΒΙΟΥ ΜΑΘΗΣΗΣ                                                                                           141,898.20
ΔΗΜΟΣ ΠΥΡΓΟΥ                                                                                                                   141,131.36
ΔΗΜΟΣ ΒΟΛΟΥ                                                                                                                    139,303.10
ΔΗΜΟΣ ΚΑΡΥΣΤΟΥ                                                                                                                 138,754.00
ΔΗΜΟΣ ΙΛΙΟΥ                                                                                                                    137,590.02
ΔΗΜΟΣ ΘΑΣΟΥ                                                                                                                    137,511.65
ΔΗΜΟΣ ΩΡΩΠΟΥ                                                                                                                   135,776.14
ΔΗΜΟΣ ΒΡΙΛΗΣΣΙΩΝ                                                                                                               132,349.10
ΔΗΜΟΣ ΠΑΡΑΝΕΣΤΙΟΥ                                                                                                              130,859.76
ΟΑΚΑ (ΣΠΥΡΟΣ ΛΟΥΗΣ)                                                                                                            128,850.00
ΔΗΜΟΣ ΠΕΡΑΜΑΤΟΣ                                                                                                                127,900.00
ΔΗΜΟΣ ΝΟΤΙΑΣ ΚΕΡΚΥΡΑΣ                                                                                                          127,190.00
ΔΗΜΟΣ ΜΟΥΖΑΚΙΟΥ                                                                                                                125,802.00
ΔΗΜΟΣ ΖΑΚΥΝΘΟΥ                                                                                                                 125,586.17
ΔΗΜΟΣ ΝΕΜΕΑΣ                                                                                                                   124,376.14
ΔΗΜΟΣ ΑΛΜΩΠΙΑΣ                                                                                                                 123,525.21
ΔΗΜΟΣ ΛΗΞΟΥΡΙΟΥ                                                                                                                123,184.96
ΔΗΜΟΣ  ΝΕΑΣ  ΦΙΛΑΔΕΛΦΕΙΑΣ - ΝΕΑΣ ΧΑΛΚΗΔΟΝΑΣ                                                                                    123,184.24
ΕΘΝΙΚΟ & ΚΑΠΟΔΙΣΤΡΙΑΚΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΑΘΗΝΩΝ                                                                                     120,995.48
ΔΗΜΟΣ ΞΑΝΘΗΣ                                                                                                                   120,934.64

In [161]:
df=df.drop_duplicates(keep="first")

In [162]:
# df[df.referenceNumber.notnull()]

In [163]:
df.duplicated().value_counts()

False    4021
Name: count, dtype: int64

In [154]:
df['contractSignedDate'] = pd.to_datetime(df['contractSignedDate'])
df = df.sort_values(by = 'contractSignedDate', ascending=True)
latest_date = df.tail(1)['contractSignedDate'].item()
one_year_before = latest_date - pd.DateOffset(years=1)
two_year_before = latest_date - pd.DateOffset(years=2)
print(f"latest date in the data: {latest_date}. \nOne year before = {one_year_before}. \nTwo years before = {two_year_before}")
df.tail(1)

latest date in the data: 2026-02-27 00:00:00.
One year before = 2025-02-27 00:00:00.
Two years before = 2024-02-27 00:00:00

,title,referenceNumber,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
8041,"ΣΥΜΒΑΣΗ ΕΥΡΩ : # 37.200,00€ #.-",26SYMV018554537,2026-02-27T19:19:46.033,2026-02-27,2026-02-28,False,2027-01-24,False,NaN,NaN,NaN,NaN,Α 02/2026,997881842,False,NaN,NaN,30000.0,NaN,1.0,8.0,Ναι,EL306,Δυτική Αττική,100015969,ΥΠΟΥΡΓΕΙΟ ΝΑΥΤΙΛΙΑΣ ΚΑΙ ΝΗΣΙΩΤΙΚΗΣ ΠΟΛΙΤΙΚΗΣ,6.0,Απευθείας ανάθεση,NaN,ΑΣΠΡΟΠΥΡΓΟΣ,193 00,Δυναμικό σύστημα αγορών,Υπηρεσίες,Βάσει τιμής,Κεντρική Κυβέρνηση,Κεντρική Διοίκηση,Εκπαίδευση,12.0,Μήνες,62ΩΒ4653ΠΩ-6ΞΧ,NaN,0878/(Α),NaN,NaN,ΑΕΝ ΑΣΠΡΟΠΥΡΓΟΥ,ΙΩΑΝΝΗΣ ΜΥΤΙΛΗΝΑΙΟΣ - Λιμενάρχης,802150294,ΣΚΑΦΙΔΑΣ ΕΥΣΤΡΑΤΙΟΣ Ε.Ε.,37200.0,30000.0,Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.- | Παροχή υπηρεσιών αποψίλωσης - κλαδονομής - καλλωπισμού και αποκομιδής καταλοίπων περιβάλλοντος χώρου Α.Ε.Ν./Ασπροπύργου διάρκειας δώδεκα (12) μηνών.-,77310000-6 | 77312000-0 | 77342000-9 | 77341000-2 | 77341000-2 | 77314000-4 | 77231200-0 | 77314000-4,Φύτευση και συντήρηση χώρων πρασίνου | Υπηρεσίες εκκαθάρισης από αγριόχορτα | Κλάδεμα θάμνων | Κλάδεμα δένδρων | Κλάδεμα δένδρων | Υπηρεσίες συντήρησης οικοπέδων | Υπηρεσίες ελέγχου παρασίτων του δάσους | Υπηρεσίες συντήρησης οικοπέδων,Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ | Δεν εμπίπτει στο ΕΣΔ,26AWRD018554440,[]

In [124]:
# missing dates - false = δεν λείπουν ημερομηνίες
df.contractSignedDate.isnull().value_counts()

contractSignedDate
False    4021
Name: count, dtype: int64

In [125]:
# hero section data validation

In [126]:
df_2026 = df[df['contractSignedDate'].between(pd.to_datetime("2026-01-01"), latest_date)]
df_2025 = df[df['contractSignedDate'].between(pd.to_datetime("2025-01-01"), one_year_before)]
df_2024 = df[df['contractSignedDate'].between(pd.to_datetime("2024-01-01"), two_year_before)]
print(f"{df_2026.shape[0]} εγγραφές από 1/1/2026 έως {latest_date}\n{df_2025.shape[0]} εγγραφές από 1/1/2025 έως {one_year_before}\n{df_2024.shape[0]} εγγραφές από 1/1/2024 έως {two_year_before}")

47 εγγραφές από 1/1/2026 έως 2026-02-27 00:00:00
91 εγγραφές από 1/1/2025 έως 2025-02-27 00:00:00
116 εγγραφές από 1/1/2024 έως 2024-02-27 00:00:00

In [132]:
spent_2026 = df_2026.totalCostWithoutVAT.sum().item()
spent_2025 = df_2025.totalCostWithoutVAT.sum().item()
spent_2024 = df_2024.totalCostWithoutVAT.sum().item()
change_cmp_2025 = round(((spent_2026 - spent_2025)/spent_2025)*100,1)
change_cmp_2024 = round(((spent_2026 - spent_2024)/spent_2024)*100,1)
print(f"Up until {latest_date} were spent {df_2026.totalCostWithoutVAT.sum().item()} euros\nThe same timeframe in 2025 were spent {df_2025.totalCostWithoutVAT.sum().item()}\nThe same timeframe in 2024 were spent {df_2024.totalCostWithoutVAT.sum().item()}")
print(f"In 2026 have been spent {change_cmp_2025}% compared to 2025 and {change_cmp_2024}% compared to 2024")

Up until 2026-02-27 00:00:00 were spent 9812963.5 euros
The same timeframe in 2025 were spent 54833220.27
The same timeframe in 2024 were spent 74908518.51999998
In 2026 have been spent -82.1% compared to 2025 and -86.9% compared to 2024

In [133]:
# Συχνότερη διαδικασία ανάθεσης
vc_2026 = df_2026.procedureType_value.value_counts()
top_type_2026 = vc_2026.idxmax()
top_count_2026 = vc_2026.max()

vc_2025 = df_2025.procedureType_value.value_counts()
top_type_2025 = vc_2025.idxmax()
top_count_2025 = vc_2025.max()

vc_2024 = df_2024.procedureType_value.value_counts()
top_type_2024 = vc_2024.idxmax()
top_count_2024 = vc_2024.max()

print(f"In 2026 the most common procedure type is {top_type_2026} with {top_count_2026} contracts\nIn 2025 the most common procedure type is {top_type_2025} with {top_count_2025} contracts\nIn 2024 the most common procedure type is {top_type_2024} with {top_count_2024} contracts")

In 2026 the most common procedure type is Απευθείας ανάθεση with 17 contracts
In 2025 the most common procedure type is Απευθείας ανάθεση (αρ.118/αρ. 328) with 50 contracts
In 2024 the most common procedure type is Απευθείας ανάθεση (αρ.118/αρ. 328) with 64 contracts

In [134]:
# ContractsPage
today = pd.Timestamp.today()
table_data = df[df['contractSignedDate'].between(latest_date-pd.DateOffset(days=27), today)].sort_values(by='contractSignedDate', ascending=False)[["contractSignedDate","organization_value", "title", "cpv_values", "firstMember_name", "procedureType_value", "totalCostWithoutVAT"]]
print(f"table data has {table_data.shape[0]} rows. Spanning from {latest_date-pd.DateOffset(days=27)} to {today}")
table_data.head(1)

table data has 28 rows. Spanning from 2026-01-31 00:00:00 to 2026-03-02 11:59:37.079441

,contractSignedDate,organization_value,title,cpv_values,firstMember_name,procedureType_value,totalCostWithoutVAT
4020,2026-02-27,ΥΠΟΥΡΓΕΙΟ ΝΑΥΤΙΛΙΑΣ ΚΑΙ ΝΗΣΙΩΤΙΚΗΣ ΠΟΛΙΤΙΚΗΣ,"ΣΥΜΒΑΣΗ ΕΥΡΩ : # 37.200,00€ #.-",Φύτευση και συντήρηση χώρων πρασίνου | Υπηρεσίες εκκαθάρισης από αγριόχορτα | Κλάδεμα θάμνων | Κλάδεμα δένδρων | Κλάδεμα δένδρων | Υπηρεσίες συντήρησης οικοπέδων | Υπηρεσίες ελέγχου παρασίτων του δάσους | Υπηρεσίες συντήρησης οικοπέδων,ΣΚΑΦΙΔΑΣ ΕΥΣΤΡΑΤΙΟΣ Ε.Ε.,Απευθείας ανάθεση,30000.0

In [142]:
df_2026[df_2026.procedureType_value=="Απευθείας ανάθεση (αρ.118/αρ. 328)"]

Empty DataFrame
Columns: [title, referenceNumber, submissionDate, contractSignedDate, startDate, noEndDate, endDate, cancelled, cancellationDate, cancellationType, cancellationReason, decisionRelatedAda, contractNumber, organizationVatNumber, greekOrganizationVatNumber, diavgeiaADA, budget, contractBudget, bidsSubmitted, maxBidsSubmitted, numberOfSections, centralGovernmentAuthority, nutsCode_key, nutsCode_value, organization_key, organization_value, procedureType_key, procedureType_value, awardProcedure, nutsCity, nutsPostalCode, centralizedMarkets, contractType, assignCriteria, classificationOfPublicLawOrganization, typeOfContractingAuthority, contractingAuthorityActivity, contractDuration, contractDurationUnitOfMeasure, contractRelatedADA, fundingDetails_cofund, fundingDetails_selfFund, fundingDetails_espa, fundingDetails_regularBudget, unitsOperator, signers, firstMember_vatNumber, firstMember_name, totalCostWithVAT, totalCostWithoutVAT, shortDescriptions, cpv_keys, cpv_values, greenContracts, auctionRefNo, paymentRefNo]
Index: []

In [109]:
table_data.duplicated().sum()

np.int64(0)

In [110]:
df.duplicated().sum()

np.int64(0)