In [1]:
import pandas as pd
import re
import requests
from datetime import date, timedelta
import unicodedata
import json
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option("display.max_colwidth", None)

In [2]:
from unicodedata import normalize as uninorm

def normalize_string(s):
    if not isinstance(s, str):
        return s
    s = s.lower()
    s = uninorm("NFD", s)
    s = "".join(c for c in s if __import__('unicodedata').category(c) != "Mn")
    s = " ".join(s.split())
    return s


def normalizeMunicipality(term):
    _TODELETE = ['ΔΗΜΟΣ', 'Δήμος', 'Δ.', ":"]
    for i in _TODELETE:
        term = normalize_string(term).replace(normalize_string(i), "")
    replacements_raw = {
        "ΝΙΚΑΙΑΣ - ΑΓΙΟΥ Ι. ΡΕΝΤΗ": "ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ",
        "ΛΙΒΑΔΕΙΑΣ" : "ΛΕΒΑΔΕΩΝ",
        "ΚΑΡΔΑΜΥΛΩΝ": "ΧΙΟΥ",
        "ΦΙΛΛΙΠΙΑΔΑΣ": "ΖΗΡΟΥ",
        "ΑΡΤΑΣ": "ΑΡΤΑΙΩΝ",
        "ΑΙΤΩΛΙΚΟΥ": "ΙΕΡΑΣ ΠΟΛΗΣ ΜΕΣΟΛΟΓΓΙΟΥ",
        "ΠΕΙΡΑΙΑ": "ΠΕΙΡΑΙΩΣ",
        "ΑΣΤΡΟΥΣ": "ΒΟΡΕΙΑΣ ΚΥΝΟΥΡΙΑΣ",
        "ΝΕΥΡΟΚΟΠΙΟΥ": "ΚΑΤΩ ΝΕΥΡΟΚΟΠΙΟΥ",
        "ΝΑΥΠΛΙΟΥ": "ΝΑΥΠΛΙΕΩΝ",
        "ΘΗΒΑΣ": "ΘΗΒΑΙΩΝ",
        "ΛΕΧΑΙΝΩΝ": "ΑΝΔΡΑΒΙΔΑΣ - ΚΥΛΛΗΝΗΣ",
        "ΖΑΚΥΝΘΙΩΝ": "ΖΑΚΥΝΘΟΥ",
        "ΕΛΑΤΙΩΝ": "ΑΜΦΙΚΛΕΙΑΣ - ΕΛΑΤΕΙΑΣ",
        "ΙΤΕΑΣ": "ΔΕΛΦΩΝ",
        "ΑΡΕΟΠΟΛΕΩΣ": "ΑΝΑΤΟΛΙΚΗΣ ΜΑΝΗΣ",
        "ΛΑΥΡΙΟΥ": "ΛΑΥΡΕΩΤΙΚΗΣ",
        "ΔΕΛΒΙΝΑΚΙΟΥ": "ΠΩΓΩΝΙΟΥ",
        "ΚΗΡΥΚΟΥ": "ΙΚΑΡΙΑΣ",
        "ΝΑΥΠΑΚΤΟΥ":"ΝΑΥΠΑΚΤΙΑΣ",
        "ΑΡΓΟΥΣ":"ΑΡΓΟΥΣ - ΜΥΚΗΝΩΝ",
        "ΜΩΛΟΥ - ΑΓ. ΚΩΝΣΤΑΝΤΙΝΟΥ":"ΚΑΜΕΝΩΝ ΒΟΥΡΛΩΝ",
        "ΚΟΡΙΝΘΟΥ":"ΚΟΡΙΝΘΙΩΝ",
        "ΛΟΥΤΡΑΚΙΟΥ - ΑΓ. ΘΕΟΔΩΡΩΝ":"ΛΟΥΤΡΑΚΙΟΥ - ΠΕΡΑΧΩΡΑΣ - ΑΓΙΩΝ ΘΕΟΔΩΡΩΝ",
        "ΣΤΑΓΥΡΩΝ - ΑΚΑΝΘΟΥ":"ΑΡΙΣΤΟΤΕΛΗ",
        "ΔΕΣΦΙΝΗΣ":"ΔΕΛΦΩΝ",
        "ΚΑΛΛΟΝΗΣ":"ΔΥΤΙΚΗΣ ΛΕΣΒΟΥ",
        "ΓΑΡΓΑΛΙΑΝΩΝ":"ΤΡΙΦΥΛΙΑΣ",
        "ΑΘΩΣ":"ΟΡΟΥΣ",
        "ΒΑΘΕΟΣ":"ΣΑΜΟΥ",
        "ΕΥΡΩΣΤΙΝΗΣ":"ΞΥΛΟΚΑΣΤΡΟΥ - ΕΥΡΩΣΤΙΝΗΣ",
        "ΕΛΕΥΘΕΡΟΥΠΟΛΗΣ":"ΠΑΓΓΑΙΟΥ",
        "ΧΡΥΣΟΥΠΟΛΗΣ":"ΝΕΣΤΟΥ",
        "ΚΡΑΝΙΔΙΟΥ":"ΕΡΜΙΟΝΙΔΑΣ",
        "ΛΑΡΙΣΑΣ":"ΛΑΡΙΣΑΙΩΝ",
        "ΕΠΤΑΧΩΡΙΟΥ":"ΒΟΙΟΥ",
        "ΒΡΥΣΣΩΝ":"ΑΠΟΚΟΡΩΝΟΥ",
        "ΔΙΚΑΙΩΝ":"ΟΡΕΣΤΙΑΔΑΣ",
        "ΘΕΣΠΡΩΤΙΚΟΥ":"ΖΗΡΟΥ",
        "ΜΕΤΑΜΟΡΦΩΣΕΩΣ": "ΜΕΤΑΜΟΡΦΩΣΗΣ",
        "ΑΚΤΙΟΥ ΒΟΝΙΤΣΑΣ": "ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ",
        "ΑΡΓΟΣ ΟΡΕΣΤΙΚΟΥ": "ΟΡΕΣΤΙΔΟΣ",
        "ΠΕΤΡΟΥΠΟΛΕΩΣ": "ΠΕΤΡΟΥΠΟΛΗΣ",
        "ΛΕΥΚΑΔΟΣ": "ΛΕΥΚΑΔΑΣ",
        "ΛΟΥΤΡΑΚΙΟΥ": "ΔΗΜΟΣ ΛΟΥΤΡΑΚΙΟΥ - ΠΕΡΑΧΩΡΑΣ - ΑΓΙΩΝ ΘΕΟΔΩΡΩΝ"
    }
    replacements = {normalize_string(k): v for k, v in replacements_raw.items()}
    
    term = re.sub(r"\s*-\s*", " - ", term)
    term = term.replace("(", "").replace(")", "")
    term = replacements.get(term, term)
    return term.upper().strip()

In [3]:
df = pd.read_csv("../data/raw_procurements.csv")
diavgeia = pd.read_csv("../data/2026_diavgeia.csv")
fires = pd.read_csv("../data/fires/fire_incidents_unified.csv")
funding = pd.read_csv("../data/funding/municipal_funding.csv")
fires['municipality_name_canonical'] = fires['municipality_name_canonical'].fillna(fires['municipality_raw'])
fires['municipality_name_canonical'] = fires['municipality_name_canonical'].apply(normalizeMunicipality)
funding['municipality_code'] = funding['municipality_code'].astype("Int64")

In [4]:
funding[1000:1200]

,year,allocation_type,recipient_type,recipient_raw,nomos,municipality_code,amount_eur,source_file,source_ada
1000,2019,τακτική,δήμος,ΤΡΙΚΚΑΙΩΝ,ΤΡΙΚΑΛΩΝ,54425,57000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1001,2019,τακτική,δήμος,ΦΑΡΚΑΔΟΝΑΣ,ΤΡΙΚΑΛΩΝ,54421,21000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1002,2019,τακτική,δήμος,ΑΜΦΙΚΛΕΙΑΣ-ΕΛΑΤΕΙΑΣ,ΦΘΙΩΤΙΔΟΣ,50721,66000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1003,2019,τακτική,δήμος,ΔΟΜΟΚΟΥ,ΦΘΙΩΤΙΔΟΣ,50706,49000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1004,2019,τακτική,δήμος,ΛΑΜΙΕΩΝ,ΦΘΙΩΤΙΔΟΣ,50711,109000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1005,2019,τακτική,δήμος,ΛΟΚΡΩΝ,ΦΘΙΩΤΙΔΟΣ,50703,83700.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1006,2019,τακτική,δήμος,ΜΑΚΡΑΚΩΜΗΣ,ΦΘΙΩΤΙΔΟΣ,50719,75000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1007,2019,τακτική,δήμος,ΚΑΜΕΝΩΝ ΒΟΥΡΛΩΝ,ΦΘΙΩΤΙΔΟΣ,50710,52000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1008,2019,τακτική,δήμος,ΣΤΥΛΙΔΑΣ,ΦΘΙΩΤΙΔΟΣ,50720,47600.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1009,2019,τακτική,δήμος,ΑΜΥΝΤΑΙΟΥ,ΦΛΩΡΙΝΗΣ,56302,45000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1010,2019,τακτική,δήμος,ΠΡΕΣΠΩΝ,ΦΛΩΡΙΝΗΣ,56306,28000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1011,2019,τακτική,δήμος,ΦΛΩΡΙΝΑΣ,ΦΛΩΡΙΝΗΣ,56308,49000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1012,2019,τακτική,δήμος,ΔΕΛΦΩΝ,ΦΩΚΙΔΟΣ,50801,128000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1013,2019,τακτική,δήμος,ΔΩΡΙΔΟΣ,ΦΩΚΙΔΟΣ,50809,77400.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1014,2019,τακτική,δήμος,ΑΡΙΣΤΟΤΕΛΗ,ΧΑΛΚΙΔΙΚΗΣ,56412,84000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1015,2019,τακτική,δήμος,ΚΑΣΣΑΝΔΡΑΣ,ΧΑΛΚΙΔΙΚΗΣ,56405,49000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1016,2019,τακτική,δήμος,ΝΕΑΣ ΠΡΟΠΟΝΤΙΔΑΣ,ΧΑΛΚΙΔΙΚΗΣ,56406,55800.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1017,2019,τακτική,δήμος,ΠΟΛΥΓΥΡΟΥ,ΧΑΛΚΙΔΙΚΗΣ,56410,90600.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1018,2019,τακτική,δήμος,ΣΙΘΩΝΙΑΣ,ΧΑΛΚΙΔΙΚΗΣ,56411,68900.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1019,2019,τακτική,δήμος,ΑΠΟΚΟΡΩΝΟΥ,ΧΑΝΙΩΝ,59413,75500.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1020,2019,τακτική,δήμος,ΓΑΥΔΟΥ,ΧΑΝΙΩΝ,59424,16700.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1021,2019,τακτική,δήμος,ΚΑΝΤΑΝΟΥ-ΣΕΛΙΝΟΥ,ΧΑΝΙΩΝ,59417,59000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1022,2019,τακτική,δήμος,ΚΙΣΣΑΜΟΥ,ΧΑΝΙΩΝ,59411,49400.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1023,2019,τακτική,δήμος,ΠΛΑΤΑΝΙΑ,ΧΑΝΙΩΝ,59418,66400.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1024,2019,τακτική,δήμος,ΣΦΑΚΙΩΝ,ΧΑΝΙΩΝ,59420,39000.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1025,2019,τακτική,δήμος,ΧΑΝΙΩΝ,ΧΑΝΙΩΝ,59423,104600.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1026,2019,τακτική,δήμος,ΟΙΝΟΥΣΣΩΝ,ΧΙΟΥ,58508,12800.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1027,2019,τακτική,δήμος,ΧΙΟΥ,ΧΙΟΥ,58509,187800.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1028,2019,τακτική,δήμος,ΗΡΩΪΚΗ ΝΗΣΟΣ ΨΑΡΩΝ,ΧΙΟΥ,58510,14600.0,6ΔΖΟ465ΧΘ7-368_τακτική_δήμοι_2019.pdf,6ΔΖΟ465ΧΘ7-368
1029,2019,τακτική,σύνδεσμος,ΣΥΝΔΕΣΜΟΣ ΔΗΜΩΝ & ΚΟΙΝΟΤΗΤΩΝ ΠΡΟΣΤΑΣΙΑΣ ΚΑΙ ΑΝΑΠΛΑΣΗΣ ΤΟΥ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΤΗΣ ΠΕΡΙΟΧΗΣ ΤΟΥ ΠΕΝΤΕΛΙΚΟΥ ΑΤΤΙΚΗΣ (ΣΠΑΠ),ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,<NA>,300000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1030,2019,τακτική,σύνδεσμος,ΣΥΝΔΕΣΜΟΣ ΠΡΟΣΤΑΣΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΥΜΗΤΤΟΥ (ΣΠΑΥ),ΑΘΗΝΩΝ,<NA>,300000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1031,2019,τακτική,σύνδεσμος,ΣΥΝΔΕΣΜΟΣ ΔΗΜΩΝ ΚΑΙ ΚΟΙΝΟΤΗΤΩΝ ΓΙΑ ΤΗΝ ΠΡΟΣΤΑΣΙΑ ΚΑΙ ΑΝΑΠΤΥΞΗ ΤΗΣ ΠΑΡΝΗΘΑΣ (ΣΥΝΠΑ),ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,<NA>,280000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1032,2019,τακτική,σύνδεσμος,ΑΝΑΠΤΥΞΙΑΚΟΣ ΣΥΝΔΕΣΜΟΣ ΔΥΤΙΚΗΣ ΑΘΗΝΑΣ (ΑΣΔΑ),ΑΘΗΝΩΝ,<NA>,250000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1033,2019,τακτική,σύνδεσμος,ΑΝΑΠΤΥΞΙΑΚΟΣ ΣΥΝΔΕΣΜΟΣ ΤΡΟΙΖΗΝΑΣ,ΠΕΙΡΑΙΩΣ,<NA>,35000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1034,2019,τακτική,σύνδεσμος,ΑΝΑΠΤΥΞΙΑΚΟΣ ΣΥΝΔΕΣΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,<NA>,150000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1035,2019,τακτική,σύνδεσμος,ΠΕΡΙΒΑΛΛΟΝΤΙΚΟΣ ΣΥΝΔΕΣΜΟΣ ΔΗΜΩΝ ΑΘΗΝΑΣ - ΠΕΙΡΑΙΑ (ΠΕΣΥΔΑΠ),ΑΘΗΝΩΝ,<NA>,175000.0,Ψ0ΜΣ465ΧΘ7-Υ78_τακτική_σύνδεσμοι_ΟΤΑ_2019.pdf,Ψ0ΜΣ465ΧΘ7-Υ78
1036,2020,τακτική,δήμος,ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ,ΑΘΗΝΩΝ,59501,27000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1037,2020,τακτική,δήμος,ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ,ΑΘΗΝΩΝ,59502,24800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1038,2020,τακτική,δήμος,ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ,ΑΘΗΝΩΝ,59503,14600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1039,2020,τακτική,δήμος,ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ-ΚΑΜΑΤΕΡΟΥ,ΑΘΗΝΩΝ,59504,24800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1040,2020,τακτική,δήμος,ΑΘΗΝΑΙΩΝ,ΑΘΗΝΩΝ,59505,118000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1041,2020,τακτική,δήμος,ΑΙΓΑΛΕΩ,ΑΘΗΝΩΝ,59506,22500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1042,2020,τακτική,δήμος,ΑΜΑΡΟΥΣΙΟΥ,ΑΘΗΝΩΝ,59508,18000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1043,2020,τακτική,δήμος,ΒΡΙΛΗΣΣΙΩΝ,ΑΘΗΝΩΝ,59510,22600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1044,2020,τακτική,δήμος,ΒΥΡΩΝΟΣ,ΑΘΗΝΩΝ,59511,27000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1045,2020,τακτική,δήμος,ΓΑΛΑΤΣΙΟΥ,ΑΘΗΝΩΝ,59512,28800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1046,2020,τακτική,δήμος,ΓΛΥΦΑΔΑΣ,ΑΘΗΝΩΝ,59513,22000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1047,2020,τακτική,δήμος,ΔΑΦΝΗΣ-ΥΜΗΤΤΟΥ,ΑΘΗΝΩΝ,59514,37600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1048,2020,τακτική,δήμος,ΕΛΛΗΝΙΚΟΥ-ΑΡΓΥΡΟΥΠΟΛΗΣ,ΑΘΗΝΩΝ,59509,26000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1049,2020,τακτική,δήμος,ΖΩΓΡΑΦΟΥ,ΑΘΗΝΩΝ,59516,24000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1050,2020,τακτική,δήμος,ΗΛΙΟΥΠΟΛΕΩΣ,ΑΘΗΝΩΝ,59517,27000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1051,2020,τακτική,δήμος,ΗΡΑΚΛΕΙΟΥ,ΑΘΗΝΩΝ,59518,19500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1052,2020,τακτική,δήμος,ΙΛΙΟΥ,ΑΘΗΝΩΝ,59519,24600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1053,2020,τακτική,δήμος,ΚΑΙΣΑΡΙΑΝΗΣ,ΑΘΗΝΩΝ,59520,32000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1054,2020,τακτική,δήμος,ΚΗΦΙΣΙΑΣ,ΑΘΗΝΩΝ,59523,79500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1055,2020,τακτική,δήμος,ΛΥΚΟΒΡΥΣΗΣ-ΠΕΥΚΗΣ,ΑΘΗΝΩΝ,59538,29500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1056,2020,τακτική,δήμος,ΜΕΤΑΜΟΡΦΩΣΕΩΣ,ΑΘΗΝΩΝ,59526,15000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1057,2020,τακτική,δήμος,ΝΕΑΣ ΙΩΝΙΑΣ,ΑΘΗΝΩΝ,59529,20000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1058,2020,τακτική,δήμος,ΠΑΠΑΓΟΥ-ΧΟΛΑΡΓΟΥ,ΑΘΗΝΩΝ,59544,38400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1059,2020,τακτική,δήμος,ΠΕΝΤΕΛΗΣ,ΑΘΗΝΩΝ,59525,75000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1060,2020,τακτική,δήμος,ΠΕΡΙΣΤΕΡΙΟΥ,ΑΘΗΝΩΝ,59536,21600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1061,2020,τακτική,δήμος,ΠΕΤΡΟΥΠΟΛΕΩΣ,ΑΘΗΝΩΝ,59537,20000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1062,2020,τακτική,δήμος,ΦΙΛΑΔΕΛΦΕΙΑΣ-ΧΑΛΚΗΔΟΝΟΣ,ΑΘΗΝΩΝ,59531,36400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1063,2020,τακτική,δήμος,ΦΙΛΟΘΕΗΣ -ΨΥΧΙΚΟΥ,ΑΘΗΝΩΝ,59545,27000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1064,2020,τακτική,δήμος,ΧΑΙΔΑΡΙΟΥ,ΑΘΗΝΩΝ,59542,25600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1065,2020,τακτική,δήμος,ΧΑΛΑΝΔΡΙΟΥ,ΑΘΗΝΩΝ,59543,20000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1066,2020,τακτική,δήμος,ΑΓΡΙΝΙΟΥ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50102,144000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1067,2020,τακτική,δήμος,ΑΚΤΙΟΥ ΒΟΝΙΤΣΑΣ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50106,44000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1068,2020,τακτική,δήμος,ΑΜΦΙΛΟΧΙΑΣ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50105,61000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1069,2020,τακτική,δήμος,ΘΕΡΜΟΥ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50110,20000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1070,2020,τακτική,δήμος,ΙΕΡΑΣ ΠΟΛΗΣ ΜΕΣΟΛΟΓΓΙΟΥ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50117,48900.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1071,2020,τακτική,δήμος,ΝΑΥΠΑΚΤΙΑΣ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50118,78000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1072,2020,τακτική,δήμος,ΞΗΡΟΜΕΡΟΥ,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,50109,43000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1073,2020,τακτική,δήμος,ΑΧΑΡΝΩΝ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59604,63000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1074,2020,τακτική,δήμος,ΒΑΡΗΣ-ΒΟΥΛΑΣ-ΒΟΥΛΙΑΓΜΕΝΗΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59606,52600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1075,2020,τακτική,δήμος,ΔΙΟΝΥΣΟΥ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59601,131700.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1076,2020,τακτική,δήμος,ΚΡΩΠΙΑΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59612,42000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1077,2020,τακτική,δήμος,ΛΑΥΡΕΩΤΙΚΗΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59613,89400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1078,2020,τακτική,δήμος,ΜΑΡΑΘΩΝΟΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59614,92800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1079,2020,τακτική,δήμος,ΜΑΡΚΟΠΟΥΛΟΥ ΜΕΣΟΓΑΙΑΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59615,18000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1080,2020,τακτική,δήμος,ΠΑΙΑΝΙΑΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59617,40000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1081,2020,τακτική,δήμος,ΠΑΛΛΗΝΗΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59608,48000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1082,2020,τακτική,δήμος,ΡΑΦΗΝΑΣ-ΠΙΚΕΡΜΙΟΥ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59619,42000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1083,2020,τακτική,δήμος,ΣΑΡΩΝΙΚΟΥ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59610,82000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1084,2020,τακτική,δήμος,ΣΠΑΤΩΝ-ΑΡΤΕΜΙΔΟΣ,ΑΝΑΤΟΛΙΚΗΣ ΑΤΤΙΚΗΣ,59620,31000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1085,2020,τακτική,δήμος,ΩΡΩΠΟΥ,ΑΝΑΤΟΛΙΚΗΣ,59646,185000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1086,2020,τακτική,δήμος,ΑΡΓΟΥΣ-ΜΥΚΗΝΩΝ,ΑΡΓΟΛΙΔΟΣ,51101,145000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1087,2020,τακτική,δήμος,ΕΠΙΔΑΥΡΟΥ,ΑΡΓΟΛΙΔΟΣ,51103,65000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1088,2020,τακτική,δήμος,ΕΡΜΙΟΝΙΔΑΣ,ΑΡΓΟΛΙΔΟΣ,51106,52000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1089,2020,τακτική,δήμος,ΝΑΥΠΛΙΕΩΝ,ΑΡΓΟΛΙΔΟΣ,51112,79000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1090,2020,τακτική,δήμος,ΒΟΡΕΙΑΣ ΚΥΝΟΥΡΙΑΣ,ΑΡΚΑΔΙΑΣ,51203,32800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1091,2020,τακτική,δήμος,ΓΟΡΤΥΝΙΑΣ,ΑΡΚΑΔΙΑΣ,51206,108000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1092,2020,τακτική,δήμος,ΜΕΓΑΛΟΠΟΛΗΣ,ΑΡΚΑΔΙΑΣ,51215,66700.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1093,2020,τακτική,δήμος,ΝΟΤΙΑΣ ΚΥΝΟΥΡΙΑΣ,ΑΡΚΑΔΙΑΣ,51213,53000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1094,2020,τακτική,δήμος,ΤΡΙΠΟΛΗΣ,ΑΡΚΑΔΙΑΣ,51219,149000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1095,2020,τακτική,δήμος,ΑΡΤΑΙΩΝ,ΑΡΤΗΣ,53105,51000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1096,2020,τακτική,δήμος,ΓΕΩΡΓΙΟΥ ΚΑΡΑΙΣΚΑΚΗ,ΑΡΤΗΣ,53108,20600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1097,2020,τακτική,δήμος,ΚΕΝΤΡΙΚΩΝ ΤΖΟΥΜΕΡΚΩΝ,ΑΡΤΗΣ,53102,28400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1098,2020,τακτική,δήμος,ΝΙΚΟΛΑΟΥ ΣΚΟΥΦΑ,ΑΡΤΗΣ,53111,20600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1099,2020,τακτική,δήμος,ΑΙΓΙΑΛΕΙΑΣ,ΑΧΑΪΑΣ,51302,119000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1100,2020,τακτική,δήμος,ΔΥΤΙΚΗΣ ΑΧΑΙΑΣ,ΑΧΑΪΑΣ,51307,78000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1101,2020,τακτική,δήμος,ΕΡΥΜΑΝΘΟΥ,ΑΧΑΪΑΣ,51320,72000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1102,2020,τακτική,δήμος,ΚΑΛΑΒΡΥΤΩΝ,ΑΧΑΪΑΣ,51309,88000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1103,2020,τακτική,δήμος,ΠΑΤΡΕΩΝ,ΑΧΑΪΑΣ,51316,130000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1104,2020,τακτική,δήμος,ΑΛΙΑΡΤΟΥ,ΒΟΙΩΤΙΑΣ,50302,35000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1105,2020,τακτική,δήμος,ΔΙΣΤΟΜΟΥ-ΑΡΑΧΟΒΑΣ- ΑΝΤΙΚΥΡΑΣ,ΒΟΙΩΤΙΑΣ,50305,37000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1106,2020,τακτική,δήμος,ΘΗΒΑΙΩΝ,ΒΟΙΩΤΙΑΣ,50307,97000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1107,2020,τακτική,δήμος,ΛΕΒΑΔΕΩΝ,ΒΟΙΩΤΙΑΣ,50310,83000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1108,2020,τακτική,δήμος,ΟΡΧΟΜΕΝΟΥ,ΒΟΙΩΤΙΑΣ,50312,39000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1109,2020,τακτική,δήμος,ΤΑΝΑΓΡΑΣ,ΒΟΙΩΤΙΑΣ,50318,79000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1110,2020,τακτική,δήμος,ΓΡΕΒΕΝΩΝ,ΓΡΕΒΕΝΩΝ,55103,125000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1111,2020,τακτική,δήμος,ΔΕΣΚΑΤΗΣ,ΓΡΕΒΕΝΩΝ,55104,26600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1112,2020,τακτική,δήμος,ΔΟΞΑΤΟΥ,ΔΡΑΜΑΣ,55203,28600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1113,2020,τακτική,δήμος,ΔΡΑΜΑΣ,ΔΡΑΜΑΣ,55202,48000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1114,2020,τακτική,δήμος,ΚΑΤΩ ΝΕΥΡΟΚΟΠΙΟΥ,ΔΡΑΜΑΣ,55204,26000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1115,2020,τακτική,δήμος,ΠΑΡΑΝΕΣΤΙΟΥ,ΔΡΑΜΑΣ,55209,37000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1116,2020,τακτική,δήμος,ΠΡΟΣΟΤΣΑΝΗΣ,ΔΡΑΜΑΣ,55206,31000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1117,2020,τακτική,δήμος,ΑΣΠΡΟΠΥΡΓΟΥ,ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ,59702,27000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1118,2020,τακτική,δήμος,ΕΛΕΥΣΙΝΑΣ,ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ,59704,36400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1119,2020,τακτική,δήμος,ΜΑΝΔΡΑΣ-ΕΙΔΥΛΛΙΑΣ,ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ,59707,101200.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1120,2020,τακτική,δήμος,ΜΕΓΑΡΕΩΝ,ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ,59708,50800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1121,2020,τακτική,δήμος,ΦΥΛΗΣ,ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ,59701,76000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1122,2020,τακτική,δήμος,ΑΓΑΘΟΝΗΣΙΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58126,12400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1123,2020,τακτική,δήμος,ΑΣΤΥΠΑΛΑΙΑΣ,ΔΩΔΕΚΑΝΗΣΟΥ,58114,16000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1124,2020,τακτική,δήμος,ΚΑΛΥΜΝΙΩΝ,ΔΩΔΕΚΑΝΗΣΟΥ,58116,29500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1125,2020,τακτική,δήμος,ΚΑΡΠΑΘΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58108,51000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1126,2020,τακτική,δήμος,ΗΡΩΙΚΗΣ ΝΗΣΟΥ ΚΑΣΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58117,12000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1127,2020,τακτική,δήμος,ΚΩ,ΔΩΔΕΚΑΝΗΣΟΥ,58118,71000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1128,2020,τακτική,δήμος,ΛΕΙΨΩΝ,ΔΩΔΕΚΑΝΗΣΟΥ,58119,11000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1129,2020,τακτική,δήμος,ΛΕΡΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58120,22000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1130,2020,τακτική,δήμος,ΜΕΓΙΣΤΗΣ,ΔΩΔΕΚΑΝΗΣΟΥ,58121,9400.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1131,2020,τακτική,δήμος,ΝΙΣΥΡΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58110,14700.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1132,2020,τακτική,δήμος,ΠΑΤΜΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58122,18000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1133,2020,τακτική,δήμος,ΡΟΔΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58123,258000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1134,2020,τακτική,δήμος,ΣΥΜΗΣ,ΔΩΔΕΚΑΝΗΣΟΥ,58124,17000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1135,2020,τακτική,δήμος,ΤΗΛΟΥ,ΔΩΔΕΚΑΝΗΣΟΥ,58113,18000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1136,2020,τακτική,δήμος,ΧΑΛΚΗΣ,ΔΩΔΕΚΑΝΗΣΟΥ,58125,11000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1137,2020,τακτική,δήμος,ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ,ΕΒΡΟΥ,57101,64000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1138,2020,τακτική,δήμος,ΔΙΔΥΜΟΤΕΙΧΟΥ,ΕΒΡΟΥ,57103,39000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1139,2020,τακτική,δήμος,ΟΡΕΣΤΙΑΔΑΣ,ΕΒΡΟΥ,57106,61000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1140,2020,τακτική,δήμος,ΣΑΜΟΘΡΑΚΗΣ,ΕΒΡΟΥ,57113,28000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1141,2020,τακτική,δήμος,ΣΟΥΦΛΙΟΥ,ΕΒΡΟΥ,57108,76600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1142,2020,τακτική,δήμος,ΔΙΡΦΥΩΝ-ΜΕΣΣΑΠΙΩΝ,ΕΥΒΟΙΑΣ,50417,69000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1143,2020,τακτική,δήμος,ΕΡΕΤΡΙΑΣ,ΕΥΒΟΙΑΣ,50423,39000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1144,2020,τακτική,δήμος,ΙΣΤΙΑΙΑΣ-ΑΙΔΗΨΟΥ,ΕΥΒΟΙΑΣ,50410,93000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1145,2020,τακτική,δήμος,ΚΑΡΥΣΤΟΥ,ΕΥΒΟΙΑΣ,50411,90000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1146,2020,τακτική,δήμος,ΚΥΜΗΣ-ΑΛΙΒΕΡΙΟΥ,ΕΥΒΟΙΑΣ,50420,113000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1147,2020,τακτική,δήμος,ΜΑΝΤΟΥΔΙΟΥ-ΛΙΜΝΗΣ-ΑΓΙΑΣ ΑΝΝΑΣ,ΕΥΒΟΙΑΣ,50409,73000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1148,2020,τακτική,δήμος,ΣΚΥΡΟΥ,ΕΥΒΟΙΑΣ,50425,30900.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1149,2020,τακτική,δήμος,ΧΑΛΚΙΔΕΩΝ,ΕΥΒΟΙΑΣ,50426,98000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1150,2020,τακτική,δήμος,ΑΓΡΑΦΩΝ,ΕΥΡΥΤΑΝΙΑΣ,50504,61000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1151,2020,τακτική,δήμος,ΚΑΡΠΕΝΗΣΙΟΥ,ΕΥΡΥΤΑΝΙΑΣ,50506,86000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1152,2020,τακτική,δήμος,ΖΑΚΥΝΘΟΥ,ΖΑΚΥΝΘΟΥ,52105,125500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1153,2020,τακτική,δήμος,ΑΝΔΡΑΒΙΔΑΣ-ΚΥΛΛΗΝΗΣ,ΗΛΕΙΑΣ,51415,90600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1154,2020,τακτική,δήμος,ΑΝΔΡΙΤΣΑΙΝΑΣ-ΚΡΕΣΤΕΝΩΝ,ΗΛΕΙΑΣ,51418,77900.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1155,2020,τακτική,δήμος,ΑΡΧΑΙΑΣ ΟΛΥΜΠΙΑΣ,ΗΛΕΙΑΣ,51405,85800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1156,2020,τακτική,δήμος,ΖΑΧΑΡΩΣ,ΗΛΕΙΑΣ,51410,41800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1157,2020,τακτική,δήμος,ΗΛΙΔΑΣ,ΗΛΕΙΑΣ,51402,51600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1158,2020,τακτική,δήμος,ΠΗΝΕΙΟΥ,ΗΛΕΙΑΣ,51409,51500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1159,2020,τακτική,δήμος,ΠΥΡΓΟΥ,ΗΛΕΙΑΣ,51417,75900.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1160,2020,τακτική,δήμος,ΑΛΕΞΑΝΔΡΕΙΑΣ,ΗΜΑΘΙΑΣ,55301,30000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1161,2020,τακτική,δήμος,ΒΕΡΟΙΑΣ,ΗΜΑΘΙΑΣ,55306,68000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1162,2020,τακτική,δήμος,ΝΑΟΥΣΑΣ,ΗΜΑΘΙΑΣ,55310,35000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1163,2020,τακτική,δήμος,ΑΡΧΑΝΩΝ-ΑΣΤΕΡΟΥΣΙΩΝ,ΗΡΑΚΛΕΙΟΥ,59120,25000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1164,2020,τακτική,δήμος,ΒΙΑΝΝΟΥ,ΗΡΑΚΛΕΙΟΥ,59105,19700.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1165,2020,τακτική,δήμος,ΓΟΡΤΥΝΑΣ,ΗΡΑΚΛΕΙΟΥ,59108,48000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1166,2020,τακτική,δήμος,ΗΡΑΚΛΕΙΟΥ,ΗΡΑΚΛΕΙΟΥ,59112,50600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1167,2020,τακτική,δήμος,ΜΑΛΕΒΙΖΙΟΥ,ΗΡΑΚΛΕΙΟΥ,59106,30800.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1168,2020,τακτική,δήμος,ΜΙΝΩΑ ΠΕΔΙΑΔΟΣ,ΗΡΑΚΛΕΙΟΥ,59114,36600.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1169,2020,τακτική,δήμος,ΦΑΙΣΤΟΥ,ΗΡΑΚΛΕΙΟΥ,59118,47500.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1170,2020,τακτική,δήμος,ΧΕΡΣΟΝΗΣΟΥ,ΗΡΑΚΛΕΙΟΥ,59109,38000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2
1171,2020,τακτική,δήμος,ΗΓΟΥΜΕΝΙΤΣΑΣ,ΘΕΣΠΡΩΤΙΑΣ,53202,58000.0,ΩΚΓΔ46ΜΤΛ6-ΝΣ2_τακτική_δήμοι_2020.pdf,ΩΚΓΔ46ΜΤΛ6-ΝΣ2

In [5]:
procurement_municipalities = list(set(df[df.organization_value.str.contains("ΔΗΜΟΣ ")]["organization_value"].tolist()))
len(procurement_municipalities)

291

In [6]:
diavgeia_municipalities = list(set(diavgeia[diavgeia.org.str.contains("ΔΗΜΟΣ ")]["org"].tolist()))
len(diavgeia_municipalities)

279

In [7]:
fires_municipalities = list(set(fires.municipality_name_canonical.tolist()))
len(fires_municipalities)

319

In [8]:
funding_municipalities = []
for i, item in funding.iterrows():
    if item['recipient_type'] == "δήμος":
        funding_municipalities.append(item['recipient_raw'])
funding_municipalities = list(set(funding_municipalities))
len(funding_municipalities)

412

In [447]:
funding_municipalities[:5]

['ΛΕΣΒΟΥ', 'ΠΑΡΓΑΣ', 'ΜΕΣΣΗΝΗΣ', 'ΣΑΜΗΣ', 'ΖΑΚΥΝΘΟΥ']

In [9]:
old_mp = pd.read_csv("/Users/troboukis/Downloads/final_entity_mapping_expanded.csv")
mp = pd.read_csv("../data/mappings/final_entity_mapping_expanded.csv")
mp["municipality_id"] = mp["municipality_id"].astype("Int64")
# mp['normalized_value'] = mp.normalized_value.apply(normalizeMunicipality)
mp.head(1)

,source_system,source_entity_type,source_key,source_value,normalized_value,municipality_id,municipality_name,region_id,match_strategy,notes
0,geo,municipality,9001,Δοξάτου,ΔΟΞΑΤΟΥ,9001,Δοξάτου,ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ ΚΑΙ ΘΡΑΚΗΣ,geo_source_of_truth,NaN

In [14]:
mp.groupby("source_system").source_entity_type.value_counts()

source_system  source_entity_type
diavgeia       organization           8253
               municipality            885
fires          municipality            974
               municipality_name       721
funding        municipality           2043
               municipality_name       417
               organization             25
geo            municipality            326
procurement    municipality            889
procurements   organization          14978
Name: count, dtype: int64

In [449]:
# r = []
# for i in procurement_municipalities:
#     j={}
#     j['source_system'] = 'procurement'
#     j['source_entity_type'] = 'municipality'
#     j['source_value'] = i
#     j['normalized_value'] = normalizeMunicipality(i)
#     r.append(j)

# k = pd.DataFrame(r)
# k.head(2)

In [450]:
# r = []
# for i in diavgeia_municipalities:
#     j={}
#     j['source_system'] = 'diavgeia'
#     j['source_entity_type'] = 'municipality'
#     j['source_value'] = i
#     j['normalized_value'] = normalizeMunicipality(i)
#     r.append(j)

# k = pd.DataFrame(r)
# k.head(2)

In [451]:
# r = []
# for i in fires_municipalities:
#     j={}
#     j['source_system'] = 'fires'
#     j['source_entity_type'] = 'municipality'
#     j['source_value'] = i
#     j['normalized_value'] = normalizeMunicipality(i)
#     r.append(j)

# k = pd.DataFrame(r)
# k.head(2)

In [452]:
# r = []
# for i in funding_municipalities:
#     j={}
#     j['source_system'] = 'funding'
#     j['source_entity_type'] = 'municipality'
#     j['source_value'] = i
#     j['normalized_value'] = normalizeMunicipality(i)
#     r.append(j)

# k = pd.DataFrame(r)
# k.head(2)

  source_system source_entity_type source_value normalized_value
0       funding       municipality       ΛΕΣΒΟΥ           ΛΕΣΒΟΥ
1       funding       municipality       ΠΑΡΓΑΣ           ΠΑΡΓΑΣ

In [453]:
l = pd.merge(k, mp, how='left', left_on='normalized_value', right_on='normalized_value',suffixes=('', '_mp'))
l = l.drop(columns=["source_system_mp", "source_entity_type_mp", "source_value_mp"])

In [454]:
l.head(1)

,source_system,source_entity_type,source_value,normalized_value,source_key,municipality_id,municipality_name,region_id,match_strategy,notes
0,funding,municipality,ΛΕΣΒΟΥ,ΛΕΣΒΟΥ,9261,9261,Λέσβου,ΒΟΡΕΙΟΥ ΑΙΓΑΙΟΥ,geo_source_of_truth,NaN

In [455]:
new_mp = pd.concat([mp, l], ignore_index=True)

In [459]:
new_mp.shape

(29511, 10)

In [457]:
new_mp['normalized_value'] = new_mp['source_value'].apply(normalizeMunicipality)

In [458]:
new_mp = new_mp.drop_duplicates().reset_index(drop=True)

In [460]:
new_mp.to_csv("../data/mappings/final_entity_mapping_expanded.csv", index=False)

In [434]:
new_mp.head(1)

,source_system,source_entity_type,source_key,source_value,normalized_value,municipality_id,municipality_name,region_id,match_strategy,notes
0,geo,municipality,9001,Δοξάτου,ΔΟΞΑΤΟΥ,9001,Δοξάτου,ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ ΚΑΙ ΘΡΑΚΗΣ,geo_source_of_truth,NaN

In [435]:
new_mp.source_system.value_counts()

source_system
procurements    14978
diavgeia         9138
funding          2465
fires            1695
procurement       889
geo               326
Name: count, dtype: int64

In [436]:
f = list(set(new_mp[(new_mp['source_system']=='funding') & (new_mp['normalized_value'].notna())]['normalized_value'].tolist()))
p = list(set(new_mp[(new_mp['source_system']=='procurement') & (new_mp['normalized_value'].notna())]['normalized_value'].tolist()))
print(f"funding has {len(f)} municipalities\nprocurement has {len(p)} municipalities")

funding has 362 municipalities
procurement has 291 municipalities

In [437]:
df.head(1)

,title,referenceNumber,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
0,ΜΙΣΘΩΣΗ ΙΔΙΩΤΙΚΩΝ ΜΗΧΑΝΗΜΑΤΩΝ ΓΙΑ ΕΚΤΕΛΕΣΗ ΕΡΓΑΣΙΩΝ ΕΚΤΑΚΤΩΝ ΑΝΑΓΚΩΝ(ΒΙΕΝΝΑ ΧΡΙΣΤΙΝΑ),24SYMV014279531,2024-02-17T12:45:08.845,0023-09-17,0023-09-17,False,NaN,False,NaN,NaN,NaN,NaN,ΧΩΡΙΣ ΠΡΩΤΟΚΟΛΛΟ,997947718,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EL641,Βοιωτία,5013,ΠΕΡΙΦΕΡΕΙΑ ΣΤΕΡΕΑΣ ΕΛΛΑΔΑΣ,6.0,Απευθείας ανάθεση (αρ.118/αρ. 328),NaN,NaN,NaN,NaN,Υπηρεσίες,NaN,NaN,NaN,NaN,NaN,NaN,Ψ2Κ37ΛΗ-ΡΚΜ,NaN,NaN,NaN,NaN,ΤΜΗΜΑ ΠΟΛΙΤΙΚΗΣ ΠΡΟΣΤΑΣΙΑΣ ΠΕ ΒΟΙΩΤΙΑΣ,ΦΑΝΗΣ ΣΠΑΝΟΣ - ΠΕΡΙΦΕΡΕΙΑΡΧΗΣ,159003964,ΒΙΕΝΝΑ ΧΡΙΣΤΙΝΑ,9721.6,7840.0,ΕΡΓΑΣΙΕΣ ΠΡΟΛΗΨΗΣ ΔΑΣΙΚΩΝ ΠΥΡΚΑΓΙΩΝ ΣΤΗΝ ΕΥΡΥΤΕΡΗ ΠΕΡΙΟΧΗ ΤΗΣ Π.Ε ΒΟΙΩΤΙΑΣ,75251110-4,Υπηρεσίες πρόληψης πυρκαγιών,Δεν εμπίπτει στο ΕΣΔ,NaN,[]

In [438]:
[x for x in f if x not in p]

['ΛΕΣΒΟΥ',
 'ΑΣΤΥΠΑΛΑΙΑΣ',
 'ΝΙΣΥΡΟΥ',
 'ΚΑΛΥΜΝΙΩΝ',
 'ΦΙΛΑΔΕΛΦΕΙΑΣ - ΧΑΛΚΗΔΟΝΟΣ',
 'ΜΙΝΩΑ ΠΕΔΙΑΔΑΣ',
 'ΑΝΑΠΤΥΞΙΑΚΟΣ ΣΥΝΔΕΣΜΟΣ ΔΥΤΙΚΗΣ ΑΘΗΝΑΣ ΑΣΔΑ',
 'ΑΓΑΘΟΝΗΣΙΟΥ',
 'ΧΑΙΔΑΡΙΟΥ',
 'ΣΟΦΑΔΩΝ',
 'ΜΕΤΣΟΒΟΥ',
 'ΣΙΝΤΙΚΗΣ',
 'ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ',
 'ΣΥΝΔΕΣΜΟΣ ΔΗΜΩΝ & ΚΟΙΝΟΤΗΤΩΝ ΠΡΟΣΤΑΣΙΑΣ ΚΑΙ ΑΝΑΠΛΑΣΗΣ ΤΟΥ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΤΗΣ ΠΕΡΙΟΧΗΣ ΤΟΥ ΠΕΝΤΕΛΙΚΟΥ ΑΤΤΙΚΗΣ ΣΠΑΠ',
 'ΗΛΙΟΥΠΟΛΕΩΣ',
 'ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ',
 'ΜΑΡΩΝΕΙΑΣ - ΣΑΠΩΝ',
 'ΚΙΛΕΛΕΡ',
 'ΧΑΛΚΗΔΟΝΟΣ',
 'ΠΥΔΝΑΣ - ΚΟΛΙΝΔΡΟΥ',
 'ΑΝΑΦΗΣ',
 'ΜΕΓΙΣΤΗΣ',
 'ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ',
 'ΑΚΤΙΟΥ ΒΟΝΙΤΣΑΣ',
 'ΔΕΣΚΑΤΗΣ',
 'ΦΟΛΕΓΑΝΔΡΟΥ',
 'ΑΡΓΟΥΣ ΟΡΕΣΤΙΚΟΥ',
 'ΚΕΦΑΛΟΝΙΑΣ',
 'ΑΡΓΟΣ ΟΡΕΣΤΙΚΟΥ',
 'ΝΑΥΠΑΚΤΙΑΣ',
 'ΠΑΤΜΟΥ',
 'ΞΗΡΟΜΕΡΟΥ',
 'ΑΝΑΠΤΥΞΙΑΚΟΣ ΣΥΝΔΕΣΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ',
 'ΑΛΕΞΑΝΔΡΕΙΑΣ',
 'ΠΕΡΙΒΑΛΛΟΝΤΙΚΟΣ ΣΥΝΔΕΣΜΟΣ ΔΗΜΩΝ ΑΘΗΝΑΣ - ΠΕΙΡΑΙΑ ΠΕΣΥΔΑΠ',
 'ΑΙΓΙΝΑΣ',
 'ΚΕΝΤΡΙΚΗΣ ΚΕΡΚΥΡΑΣ & ΔΙΑΠΟΝΤΙΩΝ ΝΗΣΩΝ',
 'ΠΕΤΡΟΥΠΟΛΕΩΣ',
 'ΚΑΛΑΜΠΑΚΑΣ',
 'ΛΕΥΚΑΔΟΣ',
 'ΣΗΤΕΙΑΣ',
 'ΝΑΟΥΣΑΣ',
 'ΣΑΜΟΥ',
 'ΕΜΜΑΝΟΥΗΛ ΠΑΠΠΑ',
 'ΘΗΡΑΣ',
 'ΤΡΙΦΥΛΙΑΣ',
 'ΚΕΦΑΛΛΟΝΙΑΣ',
 'ΣΥΝΔΕΣΜΟΣ ΟΤΑ ΔΗΜΩΝ ΒΑΘΕΩΣ ΠΥΘΑΓΟΡΕΙΟΥ',
 'ΜΙΝΩΑ ΠΕΔΙΑΔΟΣ',
 'ΤΗΛΟΥ',
 'ΚΟΡΥΔΑΛΛΟΥ',
 'ΚΥΘΝΟΥ',
 'ΤΡΙΦΥΛΛΙΑΣ',
 'ΚΕΡΚΥΡΑΣ',
 'ΤΡΟΙΖΗΝΙΑΣ',
 'ΛΟΥΤΡΑΚΙΟΥ - ΑΓΙΩΝ ΘΕΟΔΩΡΩΝ',
 'ΝΑΞΟΥ ΚΑΙ ΜΙΚΡΩΝ ΚΥΚΛΑΔΩΝ',
 'ΣΥΝΔΕΣΜΟΣ ΠΡΟΣΤΑΣΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΥΜΗΤΤΟΥ ΣΠΑΥ',
 'ΗΡΩΙΚΗΣ ΠΟΛΗΣ ΝΑΟΥΣΑΣ',
 'ΑΛΙΑΡΤΟΥ - ΘΕΣΠΙΕΩΝ',
 'ΣΕΡΒΙΩΝ - ΒΕΛΒΕΝΤΟΥ',
 'ΕΡΕΤΡΙΑΣ',
 'ΑΜΑΡΙΟΥ',
 'ΗΡΩΙΚΗΣ ΠΟΛΕΩΣ ΝΑΟΥΣΑΣ',
 'ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ',
 'ΑΝΑΠΤΥΞΙΑΚΟΣ ΣΥΝΔΕΣΜΟΣ ΤΡΟΙΖΗΝΑΣ',
 'ΜΩΛΟΥ - ΑΓΙΟΥ ΚΩΝΣΤΑΝΤΙΝΟΥ',
 'ΓΟΡΤΥΝΑΣ',
 'ΗΡΩΙΚΗ ΝΗΣΟΣ ΨΑΡΩΝ',
 'ΗΡΩΙΚΗΣ ΝΗΣΟΥ ΚΑΣΟΥ',
 'ΑΓΙΟΥ ΕΥΣΤΡΑΤΙΟΥ',
 'ΗΡΩΙΚΗΣ ΝΗΣΟΥ ΨΑΡΩΝ',
 'ΣΥΝΔΕΣΜΟΣ ΔΗΜΩΝ ΚΑΙ ΚΟΙΝΟΤΗΤΩΝ ΓΙΑ ΤΗΝ ΠΡΟΣΤΑΣΙΑ ΚΑΙ ΑΝΑΠΤΥΞΗ ΤΗΣ ΠΑΡΝΗΘΑΣ ΣΥΝΠΑ',
 'ΚΕΝΤΡΙΚΩΝ ΤΖΟΥΜΕΡΚΩΝ',
 'ΧΑΛΚΗΣ',
 'ΙΑΣΜΟΥ']

# Analysis validation

In [265]:
df['contractSignedDate'] = pd.to_datetime(df['contractSignedDate'])
df = df.sort_values(by = 'contractSignedDate', ascending=True)
latest_date = df.tail(1)['contractSignedDate'].item()
one_year_before = latest_date - pd.DateOffset(years=1)
two_year_before = latest_date - pd.DateOffset(years=2)
print(f"latest date in the data: {latest_date}. \nOne year before = {one_year_before}. \nTwo years before = {two_year_before}")
df.tail(1)

latest date in the data: 2026-03-04 00:00:00.
One year before = 2025-03-04 00:00:00.
Two years before = 2024-03-04 00:00:00

,title,referenceNumber,submissionDate,contractSignedDate,startDate,noEndDate,endDate,cancelled,cancellationDate,cancellationType,cancellationReason,decisionRelatedAda,contractNumber,organizationVatNumber,greekOrganizationVatNumber,diavgeiaADA,budget,contractBudget,bidsSubmitted,maxBidsSubmitted,numberOfSections,centralGovernmentAuthority,nutsCode_key,nutsCode_value,organization_key,organization_value,procedureType_key,procedureType_value,awardProcedure,nutsCity,nutsPostalCode,centralizedMarkets,contractType,assignCriteria,classificationOfPublicLawOrganization,typeOfContractingAuthority,contractingAuthorityActivity,contractDuration,contractDurationUnitOfMeasure,contractRelatedADA,fundingDetails_cofund,fundingDetails_selfFund,fundingDetails_espa,fundingDetails_regularBudget,unitsOperator,signers,firstMember_vatNumber,firstMember_name,totalCostWithVAT,totalCostWithoutVAT,shortDescriptions,cpv_keys,cpv_values,greenContracts,auctionRefNo,paymentRefNo
4754,"Σύμβαση αξίας 30.690,00 με φπα 24% για Υποστηρικτικές εργασίες για τη σύνταξη μελέτης για τον σχεδι",26SYMV018579344,2026-03-04T14:04:30.487,2026-03-04,2026-03-04,False,2026-06-03,False,NaN,NaN,NaN,NaN,76715,090273987,True,NaN,NaN,24750.0,NaN,2.0,1.0,Ναι,EL611,"Καρδίτσα, Τρίκαλα",100015996,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,6.0,Απευθείας ανάθεση,NaN,ΚΑΛΑΜΠΑΚΑ,42200,Δεν χρησιμοποιείται,Υπηρεσίες,Βάσει τιμής,Κεντρική Κυβέρνηση,Κεντρική Διοίκηση,Γενικές δημόσιες υπηρεσίες,3.0,Μήνες,ΨΑΧ646Ψ844-ΩΕΡ,NaN,"02.001.2310189, 02.001.23104",NaN,NaN,ΔΑΣΑΡΧΕΙΟ ΚΑΛΑΜΠΑΚΑΣ,ΖΩΗ ΦΤΙΚΑ - Αναπληρωτής Γενικός Διευθυντής,042770790,ΜΟΥΛΑΣ ΓΕΩΡΓΙΟΣ,30690.0,24750.0,"Σύμβαση με τίτλο: «Υποστηρικτικές εργασίες για τη σύνταξη μελέτης για τον σχεδιασμό αντιπυρικής προστασίας στα περιαστικά Δάση Προφήτη Ηλία Τ.Κ. Καλαμπάκας και παρυφών των βράχων των Μετεώρων», αρμοδιότητας του Δασαρχείου Καλαμπάκας, στο πλαίσιο του Χρηματοδοτικού Προγράμματος του Πράσινου Ταμείου “Προστασία και αναβάθμιση Δασών 2026” Άξονας Προτεραιότητας 5, Μέτρο , Έργο 53",75251110-4,Υπηρεσίες πρόληψης πυρκαγιών,Δεν εμπίπτει στο ΕΣΔ,26AWRD018562637,[]

In [266]:
# missing dates - false = δεν λείπουν ημερομηνίες
df.contractSignedDate.isnull().value_counts()

contractSignedDate
False    4755
Name: count, dtype: int64

In [267]:
# hero section data validation

In [268]:
df_2026 = df[df['contractSignedDate'].between(pd.to_datetime("2026-01-01"), latest_date)]
df_2025 = df[df['contractSignedDate'].between(pd.to_datetime("2025-01-01"), one_year_before)]
df_2024 = df[df['contractSignedDate'].between(pd.to_datetime("2024-01-01"), two_year_before)]
print(f"{df_2026.shape[0]} εγγραφές από 1/1/2026 έως {latest_date}\n{df_2025.shape[0]} εγγραφές από 1/1/2025 έως {one_year_before}\n{df_2024.shape[0]} εγγραφές από 1/1/2024 έως {two_year_before}")

65 εγγραφές από 1/1/2026 έως 2026-03-04 00:00:00
117 εγγραφές από 1/1/2025 έως 2025-03-04 00:00:00
133 εγγραφές από 1/1/2024 έως 2024-03-04 00:00:00

In [269]:
spent_2026 = df_2026.totalCostWithoutVAT.sum().item()
spent_2025 = df_2025.totalCostWithoutVAT.sum().item()
spent_2024 = df_2024.totalCostWithoutVAT.sum().item()
change_cmp_2025 = round(((spent_2026 - spent_2025)/spent_2025)*100,1)
change_cmp_2024 = round(((spent_2026 - spent_2024)/spent_2024)*100,1)
print(f"Up until {latest_date} were spent {df_2026.totalCostWithoutVAT.sum().item()} euros\nThe same timeframe in 2025 were spent {df_2025.totalCostWithoutVAT.sum().item()}\nThe same timeframe in 2024 were spent {df_2024.totalCostWithoutVAT.sum().item()}")
print(f"In 2026 have been spent {change_cmp_2025}% compared to 2025 and {change_cmp_2024}% compared to 2024")

Up until 2026-03-04 00:00:00 were spent 10319597.62 euros
The same timeframe in 2025 were spent 75304902.21000001
The same timeframe in 2024 were spent 78837782.85
In 2026 have been spent -86.3% compared to 2025 and -86.9% compared to 2024

In [270]:
# Συχνότερη διαδικασία ανάθεσης
vc_2026 = df_2026.procedureType_value.value_counts()
top_type_2026 = vc_2026.idxmax()
top_count_2026 = vc_2026.max()

vc_2025 = df_2025.procedureType_value.value_counts()
top_type_2025 = vc_2025.idxmax()
top_count_2025 = vc_2025.max()

vc_2024 = df_2024.procedureType_value.value_counts()
top_type_2024 = vc_2024.idxmax()
top_count_2024 = vc_2024.max()

print(f"In 2026 the most common procedure type is {top_type_2026} with {top_count_2026} contracts\nIn 2025 the most common procedure type is {top_type_2025} with {top_count_2025} contracts\nIn 2024 the most common procedure type is {top_type_2024} with {top_count_2024} contracts")

In 2026 the most common procedure type is Απευθείας ανάθεση with 32 contracts
In 2025 the most common procedure type is Απευθείας ανάθεση (αρ.118/αρ. 328) with 58 contracts
In 2024 the most common procedure type is Απευθείας ανάθεση (αρ.118/αρ. 328) with 78 contracts

In [271]:
# ContractsPage
today = pd.Timestamp.today()
table_data = df[df['contractSignedDate'].between(latest_date-pd.DateOffset(days=27), today)].sort_values(by='contractSignedDate', ascending=False)[["contractSignedDate","organization_value", "title", "cpv_values", "firstMember_name", "procedureType_value", "totalCostWithoutVAT"]]
print(f"table data has {table_data.shape[0]} rows. Spanning from {latest_date-pd.DateOffset(days=27)} to {today}")
table_data.head(1)

table data has 38 rows. Spanning from 2026-02-05 00:00:00 to 2026-03-06 11:44:50.227413

,contractSignedDate,organization_value,title,cpv_values,firstMember_name,procedureType_value,totalCostWithoutVAT
4754,2026-03-04,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,"Σύμβαση αξίας 30.690,00 με φπα 24% για Υποστηρικτικές εργασίες για τη σύνταξη μελέτης για τον σχεδι",Υπηρεσίες πρόληψης πυρκαγιών,ΜΟΥΛΑΣ ΓΕΩΡΓΙΟΣ,Απευθείας ανάθεση,24750.0

In [272]:
df_2026[df_2026.procedureType_value=="Απευθείας ανάθεση (αρ.118/αρ. 328)"]

Empty DataFrame
Columns: [title, referenceNumber, submissionDate, contractSignedDate, startDate, noEndDate, endDate, cancelled, cancellationDate, cancellationType, cancellationReason, decisionRelatedAda, contractNumber, organizationVatNumber, greekOrganizationVatNumber, diavgeiaADA, budget, contractBudget, bidsSubmitted, maxBidsSubmitted, numberOfSections, centralGovernmentAuthority, nutsCode_key, nutsCode_value, organization_key, organization_value, procedureType_key, procedureType_value, awardProcedure, nutsCity, nutsPostalCode, centralizedMarkets, contractType, assignCriteria, classificationOfPublicLawOrganization, typeOfContractingAuthority, contractingAuthorityActivity, contractDuration, contractDurationUnitOfMeasure, contractRelatedADA, fundingDetails_cofund, fundingDetails_selfFund, fundingDetails_espa, fundingDetails_regularBudget, unitsOperator, signers, firstMember_vatNumber, firstMember_name, totalCostWithVAT, totalCostWithoutVAT, shortDescriptions, cpv_keys, cpv_values, greenContracts, auctionRefNo, paymentRefNo]
Index: []

In [109]:
table_data.duplicated().sum()

np.int64(0)

In [110]:
df.duplicated().sum()

np.int64(0)